### ISSUE TITLE
Error Messages about timezone and dropbox

### ISSUE THREAD

**Issue by dennisheinzen** [sebastianfeldmann/phpbu#1]
Hi Sbas,

alles fit?
will continue in english now for the github users.

Nice tool you are doing there. Tried it on one of my servers.
Found some bugs.
First is a timezone error which php is complaining about.
And on the last line i get an error message about dropbox.

Here is the output:

<pre><code>#php phpbu.phar --configuration=myconf.xml

phpbu 1.1.2

Configuration read from myconf.xml

PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///root/git/phpbu.phar/Util/String.php on line 32
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///root/git/phpbu.phar/Util/String.php on line 32
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///root/git/phpbu.phar/Util/String.php on line 32
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///root/git/phpbu.phar/Util/String.php on line 32
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///root/git/phpbu.phar/Util/String.php on line 32
PHP Fatal error:  Class 'phpbu\Backup\Sync\dbx\WriteMode' not found in phar:///root/git/phpbu.phar/Backup/Sync/Dropbox.php on line 85</code></pre>

Here is my php version:

<pre><code>#php -version

PHP 5.6.5-1~dotdeb.1 (cli) (built: Jan 28 2015 05:40:56) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies</code></pre>

Running on:

<pre><code>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy</code></pre>

**Comment by sebastianfeldmann** [comment]
Hi Dennis
    PHP Warning:  date(): It is not safe to rely on the system's timezone settings..
This is easy to fix, you should set an date.timezone setting within you php.ini
On your debian system you most likely find the php.ini used for execution of php in CLI mode under
**/etc/php5/cli/php.ini**
Just replace

    ;date.timezone =

with

    date.timezone = Europe/Berlin

I will look into this Dropbox error

**Comment by dennisheinzen** [comment]
Date/time is set now. Error message is gone.

**Comment by sebastianfeldmann** [comment]
I just released version 1.1.3 with a fix for the error you encountered.
Just run

    $ phpbu.phar --self-update

This should upgrade phpbu to the latest version.

**Comment by dennisheinzen** [comment]
Yes, sync with dropbox works now too.

**Comment by sebastianfeldmann** [comment]
Thanks for reporting this. Enjoy your backups ;)
