### ISSUE TITLE
Do not create target dirs for some sources

### ISSUE THREAD

**Issue by F21** [sebastianfeldmann/phpbu#10]
I am currently working on the XtraBackup source. One annoying problem is that `innobackupex` will refuse to backup if the folder to store the backups in already exist. This is a safety feature to prevent accidental overwrites of backups. However, it also exits when the target folder is empty (which is really annoying!). This issue is documented [here](https://bugs.launchpad.net/percona-xtrabackup/+bug/1162952), but it is uncertain when the problem will be fixed.

Would it be possible if phpbu is updated so that sources can signal whether it wants the target directory  created? This would provide a nice work around to fix the problem.

**Comment by sebastianfeldmann** [comment]
This could be done, but i think it is not the right way to bloat the configuration to hanlde external "bugs".
I think the best way is to use a non existing subdirectory something like
```
$dumpDir = $target->getPath() . '/dump';
```
Or create a directory with a random name to realy make sure it doesn't exist.

As said in Issue #9, maybe the best way to handle this kind of sources is to enable a communication from the `Source` back to the application.
Then the `Source` should tell the application that the currently uncompressed backup is located in `$dumpDir` and still needs to be compressed.

What do you think?

**Comment by F21** [comment]
Let's close this and discuss in #9  :smile:
