### ISSUE TITLE
Change the Subject on email notifications (Feature request)

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#100]
I am using this on 3 different servers and all of them have the same subject on the emails: 
"PHPBU backup report from localhost"
It would be great to be able to customise that subject line. 
I see that the localhost came from the "server name". Maybe we can change that name too manually for the log and the email. 

Thanks!

**Comment by sebastianfeldmann** [comment]
According to https://github.com/sebastianfeldmann/phpbu/blob/master/src/Log/Mail.php#L151 this should already work.

Just include the following option and it hopefully works.

```xml
<option name="subject" value="My subject line from server XYZ" />
```

I have to update the documentation and the examples on this.

**Comment by planetahuevo** [comment]
Oh, that was great! Thank you!
