### ISSUE TITLE
Fix error on windows: Cannot connect to 

### ISSUE THREAD

**Issue by andrelopez** [sebastianfeldmann/phpbu#101]
Hi Sebastian! very nice library!
I was testing this tool on windows and I got the next error:

Exception 'phpbu\App\Exception' with message 'tar failed: tar (child): Cannot connect to C: resolve failed /usr/bin/tar: C\:/MAMP/htdocs/.......

I did some research, and I found this: 

> The reason is that tar interprets colons (:) in file names as meaning it is a file on another machine. You can disable this behavior by using the flag --force-local.

https://stackoverflow.com/a/37996249

So the solution is add the --force-local on the phpbu\App\Cli\Executable\Tar file at the createProcess function:

```
    /**
     * Process generator
     */
    protected function createProcess()
    {
        $this->validateSetup();

        $process = new Process();
        $tar     = new Cmd($this->binary);

        foreach ($this->excludes as $path) {
            $tar->addOption('--exclude', $path);
        }

        $tar->addOptionIfNotEmpty('--ignore-failed-read', $this->ignoreFailedRead, false);
        $tar->addOptionIfNotEmpty('--use-compress-program', $this->compressProgram);
        $tar->addOption('-' . (empty($this->compressProgram) ? $this->compression : '') . 'cf');
        $tar->addArgument($this->tarPathname);
        $tar->addOption('-C', dirname($this->path), ' ');
        $tar->addArgument(basename(($this->path)));
        /* Added to work on windows */
        $tar->addOption('--force-local');

        $process->addCommand($tar);

        // delete the source data if requested
        if ($this->removeSourceDir) {
            $process->addCommand($this->getRmCommand());
        }

        return $process;
    }

```

Let me know If I can help on anything else,
Keep up the good work!

**Comment by sebastianfeldmann** [comment]
Hi, thanks for the great analysis.
I will add the `--force-local` option asap ;)

**Comment by sebastianfeldmann** [comment]
I just released phpbu 4.0.10 you can now add

```xml
<option name="forceLocal" value="true" />
```
to your `tar` configuration and the `--force-local` option will be applied to the tar command.

Hope that helps ;)
Cheers, Sebastian

**Comment by andrelopez** [comment]
It works like a charm!  

Thank you.

**Comment by sebastianfeldmann** [comment]
Thank you for investigating this and making it an easy fix!
