### ISSUE TITLE
High CPU use

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#104]
Hi, 
I am having a big CPU use when backing my server up with phpbu. 
I am only using myslqdump and tar so I suspect that TAR is the problem being a lot of files to pack. 
I have found this which could be a great feature to add.
https://unix.stackexchange.com/questions/39722/preventing-tar-from-using-too-much-cpu-and-disk-old-laptop-crashes-if-100

Of course being able to do incremental backups and things like that will be better but the solution on that link is a much easier solution for the meantime. 

Thanks!

**Comment by j7an** [comment]
Would using Percona XtraBackup add to the high CPU or reduce it since it supports "hot backup"?

**Comment by sebastianfeldmann** [comment]
I'm a bit confused. The problem here is that combining and compressing a lot of small files with tar could lead to a high CPU usage.
In case of XtraBackup for MySQL the execution of any backup adds to the CPU usage.
My experience with "hot backup" with XtraBackup is that the load increase is recognizable but not a big problem. Of course, this always depends on your use case and your environment.

**Comment by planetahuevo** [comment]
Yep, for me,  I think TAR is the problem and not MySQL.

**Comment by planetahuevo** [comment]
Hi, do you have any ETA for this? 
Last backup took 100% of the CPU for 4 hours... that is too much to handle... 
It is a 10Gb website but adding the pipeline option will solve this problem. 
Thanks!

**Comment by sebastianfeldmann** [comment]
No real ETA but I hope I can have a look at this soonish ;)

**Comment by sebastianfeldmann** [comment]
I just added a new option to the `tar` source

```xml
<option name="throttle" value="5m" />
```

This way it will pipe its stream via `pv` make sure you have it installed.
To test this you can install `dev-master`. I will release version 5.0.2 hopefully later this evening.

**Comment by sebastianfeldmann** [comment]
phpbu 5.0.2 is out you can have a look at the [documentation](https://phpbu.de/manual/current/en/source.html#source.tar.throttling)

**Comment by planetahuevo** [comment]
Uau. Amazing. Thank you very much. 
Installing and testing 5.0.2 today. I will let you know how it goes.
