### ISSUE TITLE
Adding variables to config file o having a main config

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#107]
Hi, another question. 
I want to create a config file generic for a lot of users on my server.
Because of this, I need to replace the username on several places around the xml file. 
Is there any way to create a "variable" that I can capture and user all over the same config file? Like a placeholder.

Also another idea is to have a generic phpbu.xml config file with all the common things and another custom for the user config file for the thing that do not repeat. 

Maybe this could be a feature too, to have a "main config file" with defaults options that get override with the "custom config file" when needed.

For example, my email setup is always the same, the only thing I change is the subject. 
Everytime I create a new xml file, I need to copy all the options all over again.
Same for S3 and so on. 

Nothing really critical but maybe good for improvement in the future. Thanks!  :D

**Comment by sebastianfeldmann** [comment]
You can use an `Adapter` to hook some external variables into your `phpbu` config file.
Have a look at the documentation.
http://phpbu.de/manual/current/en/adapters.html

Short description:
Use a generic `phpbu.xml` file and use environment variables or a php array config file to define the changing parts.

```xml
    <option name="subject" value="adapter:MYADAPTER:email_subject" />
```

**Comment by planetahuevo** [comment]
That should work for the variables.  Thanks! 
What do you think about the "default config"?

**Comment by sebastianfeldmann** [comment]
The configuration hierarchy thing sounds a bit complex for my taste.
Especially if you have multiple backups in your default config. What kind of values do you use for what "child" configuration backup...
If you really want to do something like this you should define an own configuration format, or build the configuration in code.

**Comment by planetahuevo** [comment]
I think you are right. 
I was overthinking this too much. 
Thanks!
