### ISSUE TITLE
Getting Error with S3 multipart upload

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#108]
I am having errors when using the multipart upload for a big file.
```
Exception 'phpbu\App\Backup\Sync\Exception' with message 'An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 119: Error executing 
"UploadPart" on "https://s3-eu-west-1.amazonaws.com/XXXXXXX/XXXX-backup.bz2?partNumber=119&uploadId=u95S2JV2645NC7hZXXXXXnnG"; 
AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) ' in phar:///XXXXX/Sync/AmazonS3v3.php:49
```
Is it possible to do something about it?
maybe a "try again" feature?
Any other suggestions?
Thanks!

**Comment by misilot** [comment]
I am getting a similar response when trying to upload about a ~450MB tar file to an s3 bucket. It worked great yesterday when I set it up, now it is erroring out and not uploading the site backup.

Thanks!

```phpbu 5.2.2 by Sebastian Feldmann and contributors.

Runtime:       PHP 7.2.17
Configuration: /root/phpbu/config.xml

Time: 4 minutes 12 seconds, Memory: 14.00MB

Exception 'phpbu\App\Backup\Sync\Exception' with message 'An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 36: Error executing "UploadPart" on "https://bucket.s3.amazonaws.com/site/site-20190514-0813.tar.bz2?partNumber=36&uploadId=kapvv0b3DYmwvryQFnH5wZkzBPtMnM86W4KgmdF5JyU9KjiBSnmleGWc3JLuyNUrSskz0zfYpE4ePm1B_zgYRUl35WE_adsfdz1QO4jc2ZEtsYTnTPoY0wDkWGFoXndxAv9AE"; AWS HTTP error: Client error: `PUT https://bucket.amazonaws.com/site/site-20190514-0813.tar.bz2?partNumber=36&uploadId=kapvv0b3DYasdfmwvryQFnH5wZkzBPtMnM86W4KgmdF5JyU9KjiBSnmleGWc3JLuyNUrSskz0zfYpE4ePm1B_zgYRUl35WE_z1QO4jc2ZEtsYTnTPoY0wDkWGFoXndxAv9AE` resulted in a `400 Bad Request` response:```

**Comment by misilot** [comment]
So, I only am seeing this when I run it as a cronjob. However, if I run it directly from the console i am not having any issues.

**Comment by misilot** [comment]
As a follow up, it seems to fail when running via /bin/sh but when running via /bin/bash it works just fine. What I did was set the cronjob to run the job via bash.

**Comment by sebastianfeldmann** [comment]
I'll have a close look at the `sh` execution

**Comment by sebastianfeldmann** [comment]
After some tests I can confirm that the S3 sync is not a stable when using a `sh` shell.
I'll pull a warning in the documentation.

**Comment by misilot** [comment]
@sebastianfeldmann I just wanted to follow up to this, that when running on an EC2 instance since the end of June, I have not had an issue running the S3 sync via a ```sh``` shell.

**Comment by sebastianfeldmann** [comment]
@misilot thanks for the feedback. So no warning :)
