### ISSUE TITLE
Is it possible to change the subject if the backups is not completed?

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#110]
I am getting daily emails for my backups, which is working great. 
Sometimes my backup fails because it cannot upload it properly to the S3.
It is not a big issue and I am working to use smaller backups to fix it, but it could be a great enhancement to provide a different subject on the email if the Backup failed for anything or if the backup has been a suceded. 

That way I can filter them on my email and only get into my inbox the important ones: the failed ones.

Thanks!

**Comment by sebastianfeldmann** [comment]
I added a state flag to the mail title **[OK|WARNING|ERROR]**

This will be released with version 5.0.0

**Comment by planetahuevo** [comment]
Hi, 
I cannot find this on the docs. 
Can you put an example on how to use it? 
Thanks!

**Comment by sebastianfeldmann** [comment]
The email subject will always have different postfixes.

"Backup report from example.com **[OK]**" (all good)
"Backup report from example.com **[WARNING]**" (backup ok but sync cleanup... failed)
"Backup report from example.com **[ERROR]**" (backup failed)

You can customize your subject line.
```xml
<option name="subject" value="My Backup Subject" />
```

This will result in subjects like
"My Backup Subject **[OK]**"
...

Hope that helps.

**Comment by planetahuevo** [comment]
It does help. Thanks!

**Comment by sebastianfeldmann** [comment]
Nice ;)
