### ISSUE TITLE
Should phpbu run as backup user and group?

### ISSUE THREAD

**Issue by j7an** [sebastianfeldmann/phpbu#111]
I'm reading backup guide for Percona XtraBackup below where author suggests using system backup user and backup group for backup. Plus a backup user within mysql is created for backup purposes. Should same procedure be followed for phpbu? I will be using with either ServerPilot / RunCloud which allows creating separate users for each website.

https://www.digitalocean.com/community/tutorials/how-to-configure-mysql-backups-with-percona-xtrabackup-on-ubuntu-16-04

**Comment by sebastianfeldmann** [comment]
If you have a user that is capable of doing backups you can most certainly use it.
Most of the time users need different permissions to execute a backup then the need to execute an application.
It's never a bad idea to start with the minimal required permissions for a use case.
For example, you application user is able to read and write data.
Your backup user is able to read data and lock tables ...
Neither of them is able to create or drop tables.
If you don't mind and your application user has every necessary permission for your application and your backup you can use the same one for both tasks.
