### ISSUE TITLE
Konflikt mit swiftmailer ~6.0

### ISSUE THREAD

**Issue by benjaminfunk** [sebastianfeldmann/phpbu#112]
Hey,

wenn man swiftmailer ~ 6.0 installiert hat, lässt sich phpbu leider nicht installieren (via composer update).

**Comment by sebastianfeldmann** [comment]
Ich hab die `composer.json` so angepasst das auch Swiftmailer 6.0 akzeptiert wird.
Die von BC betroffenen Stellen habe ich auch angepasst.
Sollte also jetzt mit Version 5.0.1 funktionieren.
