### ISSUE TITLE
Request: Add a flag for simulation emails

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#115]
Hi, 
When I execute a --simulate I get exactly the same emails as I was doing the proper backup, and this sometimes is scary. 
Add a flag to those emails with a [SIMULATE] or [TEST] before the [OK][WARNING] and [ERROR] will help a lot to do testings. 

Thanks!

**Comment by sebastianfeldmann** [comment]
Nice idea

**Comment by planetahuevo** [comment]
Hi, I am testing this. 
Is there any options to use? Cannot find it on the docs. 
Thanks!

**Comment by sebastianfeldmann** [comment]
This is currently only available via dev-master, it will be released with version 5.1.0
I hope 5.1.0 will be released in the next 1 to 3 weeks (fingers crossed)
