### ISSUE TITLE
Any plan to add a restore option?

### ISSUE THREAD

**Issue by cmmata** [sebastianfeldmann/phpbu#116]
Hello!

I'm starting to use phpbu in my company, and first of all I want to thank you for building this tool! Looks great! No more manual mysqldup :)

Looking at the documentation, one feature I miss is the possibility to restore a database backup to any server (original or another one). Is there any plan to add this feature? For example, in my company we want to make sure that backups are working and are fully recoverable (to avoid problems like [Gitlab database incident](https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/)). We want to restore last dump of all configured databases in a testing server and check that the restore process went well.

We work with MySQL, PostgreSQL, and soon we'll add a SQL Server database, so I'm planning to extend phpbu to make backups of SQL Server. Would you like a PR with that new source?

**Comment by sebastianfeldmann** [comment]
Hi there,
I'm happy to hear that you find phpbu useful.

Restoring backups is a tricky thing.
My experience tells me that in most cases if you need a backup you don't need the complete backup.
Most of the time you need a special table, a specific directory or...
And if you want to use your backup to setup test environments you should not use your backup as is. For example, you should remove or obfuscate personal data of your customers.

So I'll maybe never add a feature to completely restore your backup with one simple `phpbu` command.

Never the less I'm planning to add a `--restore` option.
That will give you a list of instructions (commands) that you have to execute to restore your backup.
Starting with decompressing and decryption commands to the source specific restoring commands.
So you have some kind of guideline to restore your data depending on your configuration.

I can't really say when I will release version 5.1.0 with the `--restore` feature, my schedule is a bit packed at the moment :/

**Comment by cmmata** [comment]
I understand what you say. It's a pity, but anyway that `--restore` option could be very useful. Maybe I can develop some automation with that guide. Thank you! And don't worry, it's not something I need tomorrow or I'll die ;) Nowadays almost every developer have a killer schedule.

By the way, what about the SQL Server PR? Would you want it? If not, I can push the code in a gist or a personal repo.

**Comment by sebastianfeldmann** [comment]
Oh sorry, I have completely missed that point.
I would love a pull request for a `SQL Server Source`

**Comment by cmmata** [comment]
Okay, I'll send it as soon as I have it stable.
