### ISSUE TITLE
Mysqldump port option

### ISSUE THREAD

**Issue by andrelopez** [sebastianfeldmann/phpbu#117]
Hi Sebastian!

Could we add support for port option on mysqldump as in the pgdump ?

Other quick question: Is there a way to avoid the "debug" key on the log file? because is showing the mysql user and password for some reason and I think that is not a good idea or just show something like user: xxx, password: xxxx (I mean shows the entire mysqldump command). I have tried 'verbose' => false and debug => false on the phpbu command line tag and haven't had luck.

Thanks a lot!

**Comment by sebastianfeldmann** [comment]
Hi,
adding a port option should not be a problem.
For the password thing, this should not happen :/
I'll try to reproduce this and fix this immediately.
Maybe you can share how you execute phpbu (MySQL config, phpbu CLI options) and where you see the password in clear text.
Cheers Sebastian

**Comment by andrelopez** [comment]
Hi Sebastian,

I execute phpbu with the next command using the proc_open function (if is disabled I use exec) on php:

`cd /var/www/html/craft3/vendor/enupal/backup/src/resources && php phpbu5.phar --configuration=/var/www/html/craft3/storage/enupalbackup/config.json`

config.json
`{"verbose":false,"logging":[{"type":"json","target":"\/var\/www\/html\/website\/storage\/logs\/dbs\/website_20170914091656_sowqisrsam.log"},{"type":"webhook","options":{"uri":"http:\/\/website.dev\/webhook\/finished"}}],"backups":[{"name":"Database","source":{"type":"mysqldump","options":{"host":"localhost","databases":"website","user":"root","password":"root"}},"target":{"dirname":"\/var\/www\/html\/website\/storage\/dbs\/databases\/","filename":"database-website_20170914091656_sowqisrsam.sql"},"syncs":[{"type":"dropbox","options":{"token":"secret","path":"\/dbs\/website_20170914091656_sowqisrsam"}}]}]}`

log.log
`{"status":0,"timestamp":1505405817,"duration":8.5058,"backupCount":1,"backupFailed":0,"errorCount":0,"errors":[],"backups":[{"name":"Database","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":1,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}}],"debug":["\/usr\/bin\/mysqldump --user='root' --password='root' --host='localhost' 'website' > \/var\/www\/html\/website\/storage\/dbs\/databases\/database-website_20170914091656_sowqisrsam.sql","upload: done  (144018)"]}`


There is an option on mysqldump called: --defaults-extra-file so we can pass the credentials into a file instead of the console what do you think? please let me know if you need more info.

**Comment by sebastianfeldmann** [comment]
I created a separate bug for the masking issue.

**Comment by sebastianfeldmann** [comment]
I added the 'port' option to the latest version 5.0.3 that got release a couple of minutes ago ;)
