### ISSUE TITLE
Error when encrypt if keepUncrypted is false on windows

### ISSUE THREAD

**Issue by andrelopez** [sebastianfeldmann/phpbu#119]
Hi Sebastian!
This error just comes up on Windows, when phpbu try to delete the encrypted file it throws an error, I think it's because the "rm" command does not exists on windows, this is the error message:

`Command failed: exit-code: 1 message: "rm" is not recognized as an internal or external command, operable program or batch file ' in phar://C:/MAMP/htdocs/website/plugin/src/resources/phpbu5.phar/lib/phpdotenv/Command/Runner/Simple.php:57 `

I understand if it can be something difficult to fix, for now I will add a validation to place the `keepUncrypted ` flag in true if the OS is windows, and delete the file on my own. Please let me know if a I can help with something else.

Thank you!

**Comment by sebastianfeldmann** [comment]
Have you tried to install `cygwin` so you have at least some basic linux shell commands available like `rm`, `mv`, `ssh` and some other handy stuff ;)

**Comment by andrelopez** [comment]
Thanks Sebastian! that worked. I already had installed it but I forgot add the `cygwin\bin` folder to the Environment Variables on Windows.

**Comment by sebastianfeldmann** [comment]
Nice, i will close this then ;)
