### ISSUE TITLE
Dropbox API v1 deprecated 

### ISSUE THREAD

**Issue by immu** [sebastianfeldmann/phpbu#120]
Hi Sebastian,

I wanted to test Dropbox functionality and installed phpbu via composer (v 4.0.10).

I've seen the following line after installation:
phpbu/phpbu suggests installing dropbox/dropbox-sdk (**Require '~1.1' to sync to Dropbox**)

seems dropbox has deprecated v1
https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

can we expect Dropbox functionality with Dropbox-API-v2 ?

Thanks & Regards,
immu

**Comment by sebastianfeldmann** [comment]
Do you have to use Version 4.0.10 for php version reasons?
If you have php 7.0 or later available you can use phpbu version 5.x with Dropbox API v2 support.

If you need the Dropbox API v2 support in phpbu 4.0.x someone has to backport it manually, worst case scenario this someone is me ;)

**Comment by immu** [comment]
worst case :p ,
I use phpbu v4.0 coz, I'm using php v 5.x.

by chance, you wanna update v4 to Dropbox API v2?

Thanks for your time :)

**Comment by sebastianfeldmann** [comment]
I will have a look at it hopefully this week ;)

**Comment by cokoladasarizom** [comment]
Any news on this one?

**Comment by sebastianfeldmann** [comment]
The API lib I use with phpbu 5 has a minimum requirement of PHP 5.6.4.
Is that ok for you, or do you need to support even lower php versions?

**Comment by cokoladasarizom** [comment]
PHP 5.6.4 is ok. Thanks!

**Comment by sebastianfeldmann** [comment]
I just released a version 4 update (4.0.11) with the updated dropbox api.

I didn't do intensive testing, but I hope it works ;)

You can download the `phar` version here
https://github.com/sebastianfeldmann/phpbu/releases/tag/4.0.11

Let me know if it works as intended

Cheers, Sebastian

**Comment by cokoladasarizom** [comment]
I can confirm that it works.
Thanks Sebastian!

**Comment by sebastianfeldmann** [comment]
Awesome, thanks for the feedback :)
