### ISSUE TITLE
Adapters not being expanded

### ISSUE THREAD

**Issue by joaocc** [sebastianfeldmann/phpbu#121]
This happens in the following 2 places.
In this case, we tested with same-origin adpters and it works fine.
```
<backup name="adapter:myEnv:BAK_NAME"...
...
      <target
        dirname="adapter:myEnv:BAK_DIR"

```

**Comment by sebastianfeldmann** [comment]
Sorry I don’t understand what you are trying to say?  Can you be a bit more specific and post your adapter configuration.
What do you mean by “same-origin adapters”?

**Comment by joaocc** [comment]
Sorry about the impromptu terminology.
I have since been able to address the shortcomings using the PHP adapter.
My original setup was a .env file and a XML config file.
Some of the variables from the .env file were correctly expanded.
But, the expansion failed at the backup/name and target/dirname locations.
Thx

**Comment by joaocc** [comment]
Yes, that was what I was trying to say. Thx!
Regarding the adapters themselves, I also had some difficulty understanding if they are supported in the middle of strings (something to bash "somestring${var1}someoher${var2}")

**Comment by sebastianfeldmann** [comment]
Currently the regex is `#^adapter:([a-z0-9_\-]+):(.+)#i` so it only looks at **start** to **end**.

Finding the start wouldn't be an issue but finding the end of the adapter value would be tricky.

For example "fooadapter:myadapter:barbaz" would be impossible to determine.
I would have to change the adapter syntax to "foo:adapter:myadapter:bar:baz" to make that work.

I have to think about it, and check if I can make this work without breaking backwards compability.

**Comment by joaocc** [comment]
Alternatively, you could also support both the current syntax an a new delimited syntax such as "${....}".
Anyway I solved this using the PHP adapter, doing the concatenations there.
thx and feel free to close the bug when fixed.

**Comment by sebastianfeldmann** [comment]
With phpbu `5.0.7` you can use multiple adapter values in a single configuration value.
With multiple adapter values you have to use leading and trailing colons as well.

```xml
<option name="some" value=":adapter:foo:dir:/path/:adapter:foo:filename:.conf"/>
```
