### ISSUE TITLE
Add backup functionality for Elasticsearch

### ISSUE THREAD

**Issue by renepardon** [sebastianfeldmann/phpbu#123]
Would be nice to also have Elasticsearch available within the Backup Sources: https://phpbu.de/manual/current/en/source.html

**Comment by sebastianfeldmann** [comment]
I just wanted to post a link to the Elastic source documentation, realizing that there is no documentation available for the elastic source :/

But there is an Elasticdump implementation.
Have a look at for a config example
https://github.com/sebastianfeldmann/phpbu/blob/master/doc/config/source/elasticdump.xml
You can look at the implementation here:
https://github.com/sebastianfeldmann/phpbu/blob/master/src/Backup/Source/Elasticdump.php#L75

Hope that helps

**Comment by sebastianfeldmann** [comment]
I just added the mission Elastic documentation
https://phpbu.de/manual/current/en/source.html#source.elasticdump
