### ISSUE TITLE
Editing Factory.php when implementing custom adapter

### ISSUE THREAD

**Issue by sadreck** [sebastianfeldmann/phpbu#124]
Hi,

I've implemented a custom adapter to support remotepassword.com (so that I don't have to hardcode a password in the XML file), but in order to make it work I had to add to update Factory.php as well.

Code is here: https://github.com/sadreck/phpbu/blob/1f79ec45ebe18052514942ddd9bdd5d8be8bc04f/src/Factory.php#L37

The documentation says that you only need the file in /Adapter but that didn't seem to work for me. Is this a bug or am I missing something obvious?

Thanks,
Pavel

**Comment by sebastianfeldmann** [comment]
To use a custom Adapter you have to register it at the Factory.
This is done by using a bootstrap php file.
‘’’xml
<phpbu bootstrap=“init.php”>
‘’’
And within your bootstrap file register the Adapter.
‘’’php
use phpbu\App\Factory;

Factory::register(‘adapter’, ‘myAdapter’, MyAdapter::class);
‘’’

**Comment by sadreck** [comment]
Hi,

Thanks for the quick response.

I'm now using the bootstrap attribute but the file is never executed (even if I just put a die() statement there). Here's my XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/5.0/phpbu.xsd" bootstrap="/home/pavel/dev/phpbu/src/init.php">
    <adapters>
        <adapter type="rpass" name="rpass">
            <option name="gpgPath" value="/usr/bin/gpg"></option>
        </adapter>
    </adapters>
    <backups>
        <backup>
            <!-- source -->
            <source type="mysqldump">
                <option name="databases" value="rpass2"/>
                <option name="user" value="pavel"/>
                <option name="password" value="adapter:rpass:z0Przsb8HtP1AE07BeulDwJ4NOVWxb16cRyLjJU1dK3No3V0hqlVW5ZJTVGq6Hxi29787f0c81a64f625b0f6dd0570412adb15754647aa9f846c4084162e0877396|A654B4F3"/>
            </source>
            <!-- where should the backup be stored -->
            <target dirname="backup/mysql"
                    filename="mysqldump-%Y%m%d-%H%i.sql"
                    />
        </backup>
    </backups>
</phpbu>
```
Even when I run ./phpbu --bootstrap=file (file has a die() statement) I get:

```
./phpbu --configuration=sample.xml --bootstrap=/home/pavel/dev/phpbu/src/init.php
phpbu 5.0-dev by Sebastian Feldmann and contributors.

unknown adapter: rpass
```

I've tried seeing where it dies out and it's in https://github.com/sebastianfeldmann/phpbu/blob/master/src/Configuration/Loader/File.php#L73

I believe it breaks due to the <adapters> tag where I set the options.

Thanks,
Pavel

**Comment by sebastianfeldmann** [comment]
oO, I will look right into this ... tomorrow morning

**Comment by sebastianfeldmann** [comment]
Which version of `phpbu` are you using?

I tried this configuration

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpbu bootstrap="backup/bootstrap.php" verbose="false">
```
with this bootstrap file
```php
```

**Comment by sadreck** [comment]
Hi Sebastian,

sorry for the delay. I'm using 5.0.7 and here's what I have confirmed at the moment.

When I set an actual password it works (I get "foo"):
```
<option name="password" value="test"/>
```

When I use _any_ adapter for the password, it doesn't (no "foo" for me!).
```
<option name="password" value="adapter:rpass:somevalue"/>
```

Thanks,
Pavel

**Comment by sebastianfeldmann** [comment]
You are sorry... what should I be, I totally overlooked this the whole time.

Shame on me.

Did you manage to make sure your `bootstrap` file is executed with something similar what I posted above?
```php
<?php
// bootstrap demo file
echo "foo\n";
exit(1);
```

**Comment by sebastianfeldmann** [comment]
Forget what I said, I can reproduce your error now.

It's a chicken and eg problem.

Currently I create the configuration and setup the adapters first.
And then load the bootstrap file.
Obviously that doesn't work for `Adapters` because they are needed to create the `Configuration` in the first place.

So ... I have to restructure some things and will fix this as soon as possible.

**Comment by sebastianfeldmann** [comment]
Ok I just released phpbu 5.0.9 including a bugfix for this problem.
The bootstrap file is no included before creating the configuration.
No custom `Adapters` should work as well.

**Comment by sadreck** [comment]
Thank you Sebastian, works like a charm now!

Pavel

**Comment by sebastianfeldmann** [comment]
No worries, it took me way too long to recognize the severity of your problem and that it was an error on my side.

Thank you for letting me know that it works and reporting it in the first place.
I really appreciate it.
