### ISSUE TITLE
Tools like mysqldump and gzip can't be found

### ISSUE THREAD

**Issue by egifford** [sebastianfeldmann/phpbu#126]
This is an awesome tool. Thanks very much for building it.

I ran into an issue after updating from 4.0.10 to 5.0.7. My installs of PHPBU could no longer find external tools like mysqldump and gzip.

I think this is due to a small mistake in phpbu\App\Util\Cli::detectCmdLocationInPaths().

I've shared my fix as a pull request:
https://github.com/sebastianfeldmann/phpbu/pull/125

**Comment by sebastianfeldmann** [comment]
I merged your pull request and released version 5.0.8

Thanks again! I really appreciate it.
