### ISSUE TITLE
rsync will only create a tar file.

### ISSUE THREAD

**Issue by jdcrecur** [sebastianfeldmann/phpbu#127]
We were hoping to use  PHPBU's rsync module to create a backup of a big directory holding in excess of 100,000+ files.

We want the backup script to run every 30 minutes. Rsync is the perfect tool as it will only sync over the files that have changed...which in 30 minutes for us would only ever be a max. of 20-50 files.

PHPBU is proving excellent for database backups so we aim to use it for the file backups too.

The problem is though, PHPBU's rsync creates a tar file of the source directory, this prevents us from benefiting from rsync's built in caching system. It also prevents us from cherry picking out files from the backup drive without first uncompressing it all.

Is there a way to stop PHPBU from create a tar file?

**Comment by sebastianfeldmann** [comment]
I think you can use the `dirsync` = `true` option to indicate you don't want to create the tar.

The wording in the documentation is a bit vague
http://phpbu.de/manual/current/en/source.html#source.rsync

If you have a look at the code of the `Rsync Source` it looks exactly like what you need.
```php
if (!$this->isDirSync) {
    // induce tar compression
}
```

Let me know how that goes ;)

Cheers, Sebastian
