### ISSUE TITLE
Url or Uri parameter in webhook example

### ISSUE THREAD

**Issue by cmmata** [sebastianfeldmann/phpbu#131]
Hello,

I think there's a typo in the [webhook documentation](https://phpbu.de/manual/current/en/logging.html#logging.webhook). In the webhook example in XML, there's an option `url` that should be `uri`, if I'm not wrong.

**Comment by sebastianfeldmann** [comment]
You are absolutely right

**Comment by sebastianfeldmann** [comment]
Fixed ;)

Thanks for reporting
