### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by roberthallatt** [sebastianfeldmann/phpbu#133]
I have been doing some testing and while the backup executes perfectly, the email notification does not. I have it configured this way:

      <log type="mail">
        <option name="transport" value="smtp"/>
        <option name="smtp.port" value="587"/>
        <option name="smtp.host" value="smtp.mandrillapp.com"/>
        <option name="smtp.username" value="xxx"/>
        <option name="smtp.password" value="xxx"/>
        <option name="subject" value="PHPBU Backup Report - cpsca_ee255_1"/>
        <option name="sender.mail" value="backups@cps.ca"/>
        <option name="recipients" value="roberth@cps.ca"/>
      </log>

Am I doing something wrong?

**Comment by sebastianfeldmann** [comment]
This config is working for me
```
<log type="mail">
      <option name="recipients" value="recipient@example.com"/>
      <option name="sender.mail" value="foo@bar.de"/>
      <option name="transport" value="smtp"/>
      <option name="smtp.host" value="mail.bar.net"/>
      <option name="smtp.username" value="foo@bar.de"/>
      <option name="smtp.password" value="TopSecret"/>
      <option name="smtp.port" value="465"/>
      <option name="smtp.encryption" value="ssl"/>
</log>
```
Try adding the encryption and transport options.

**Comment by sebastianfeldmann** [comment]
Hope it is working, I'll close this issue, if you still have problems feel free to reopen this issue with further information.
