### ISSUE TITLE
rsnyc ssh rsa key

### ISSUE THREAD

**Issue by BeezleBug** [sebastianfeldmann/phpbu#134]
Is it possible to use an ssh key with rsync (source type="rsync")? If the rsnyc file backup should run via cronjob without user interaction that would be great (like in rsync via cli: rsync [...] -e "-i the/rsa/key" user@from/files to/files).

**Comment by sebastianfeldmann** [comment]
There is an 'args' option for rsync so you can use your own options and arguments.

Have a look at the documentation here.
https://phpbu.de/manual/current/en/sync.html#sync.rsync

**Comment by BeezleBug** [comment]
Thank you, I must have overlooked that "args" option. Sorry for bothering with a rtfm issue ...

**Comment by sebastianfeldmann** [comment]
No worries, hope it works ;)
