### ISSUE TITLE
Cleanups not working 

### ISSUE THREAD

**Issue by KnightAR** [sebastianfeldmann/phpbu#135]
Hello, I'm using 4.x and tested 5.x branch; Cleanups are just not deleting old files.

This is my target and cleanup parameters:

```
<target dirname="/root/sql_backups/database/%Y/%m/%d/" filename="database-%Y%m%d-%H%i.sql" compress="bzip2"/>

<cleanup type="stepwise">
  <!-- mandatory -->
  <option name="daysToKeepAll" value="2" />

  <!-- mandatory -->
  <option name="daysToKeepDaily" value="5" />

  <!-- mandatory -->
  <option name="weeksToKeepWeekly" value="3" />

  <!-- mandatory -->
  <option name="monthToKeepMonthly" value="4" />

  <!-- mandatory -->
  <option name="yearsToKeepYearly" value="10" />
</cleanup>
```

I originally had capacity of 5GB set, and my backups have grown way over that and filled the space on my server. Which points to me that the cleanups are just not working. I switched to stepwise thinking that will solve the problem but it did not.

Is it that the cleanup does not know where to look and is only cleaning up the files in the dynamic directory of the target folder? In this case, it should be looking in /root/sql_backups/database/ but I'm guessing it's looking in /root/sql_backups/database/%Y/%m/%d/ and those subfolders.

I guess the fix for now would be to remove %Y/%m/%d and store everything in the same folder?

**Comment by sebastianfeldmann** [comment]
If you configure a target directory like `/root/sql_backups/database/%Y/%m/%d` phpbu will search all matching directories for files matching your filename `database-%Y%m%d-%H%i.sql`

Cleaning backups is a 2 step process. First the `Collector` collects all matching local backups. Then the Cleaner decides which ones have to be deleted.

⚠️ If you change your target directory or filename configuration, old backups will not be collected/deleted.

For example it will look in all these matching directories for files like `database-20180102-0318.sql`.
I added a unit test to make sure that your setup works.

```
/root/sql_backups/database
                          /2017
                                /12
                                   /01
                                   /02
                          /2018
                                /01
                                   /01
                                   /02
```

After collecting all available backups the `Stepwise` `Cleaner` decides based on the file `mtime` and your configuration which files should be deleted.

If you run `phpbu --simulate` you can verify the list of backups that would be cleaned up.

Hope that helps.
