### ISSUE TITLE
In latest release 5.0.10 sync with encryption does not work

### ISSUE THREAD

**Issue by csaggo** [sebastianfeldmann/phpbu#139]
I updated the .phar to the current 5.0.10 release and did not change anything in my config.json.
But now i get the following error:
Exception 'phpbu\App\Backup\Sync\Exception' with message 'target file 'mysql-20180501-0200.sql.bz2' doesn't exist' in phar:///etc/nginx/conf.d/PHPBU/phpbu.phar/Backup/Sync/AmazonS3v3.php:49

I use the crypt option with openssl, so the filename it looks to upload to s3 should actually be mysql-20180501-0200.sql.bz2.enc

The Files are generated correctly and exist.

**Comment by sebastianfeldmann** [comment]
I'll look into this asap

**Comment by sebastianfeldmann** [comment]
You are absolutely right. I messed it up during some `--restore` preparations.

Update to version 5.0.11 and it should be fixed.

**Comment by csaggo** [comment]
Thanks so much for the quick reaction!
