### ISSUE TITLE
Investigate remote Collectors 

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianfeldmann/phpbu#144]
There are currently some issues with the remote `Collectors`

Since parts of the path could by dynamic because of date placeholders like %Y or %m
The collecting of backup files seems to be not working a 100%.

Have to make sure remote Collectors work für changing path elements as well as changing file names.

For example `backup/%y/%m/mysql-%y%m%d.sql` should collect

```
backup
  /2018
    /01
      mysql-20180101.sql
      mysql-20180102.sql
    /02
      mysql-20180201.sql
      mysql-20180202.sql
  /2017
    /12
      mysql-20181201.sql
      mysql-20181202.sql
    /11
      mysql-20181101.sql
      mysql-20181102.sql
```

- [x] Amazon s3
- [x] Dropbox
- [x] FTP
- [x] Google Drive
- [ ] OpenStack
- [x] rsync
- [x] SFTP
- [x] Softlayer (no remote cleanup implementation)

**Comment by vitalybaev** [comment]
Oh, sure, I forgot about it. I think I could fix it for all collectors today/tomorrow!

**Comment by sebastianfeldmann** [comment]
Nice

**Comment by vitalybaev** [comment]
I have following idea:
Since `Target` class have much useful logic about paths with placeholders we should use it to avoid duplications.
Collector have to get:
1) raw filename
2) path info 
So the easiest way is to pass to collector usual `Target` class with raw filename and remote path in constructor.
So we could use `Target` methods for determine path that isn't changing and do our work

What do you think?

**Comment by sebastianfeldmann** [comment]
I thought about that as well.
My idea was to extract the path logic to some helper classes like
\phpbu\App\Backup\Target\Path
and
\phpbu\App\Backup\Target\Path\Element
or something similar.
And then use those in Target and remote collectors.

**Comment by vitalybaev** [comment]
Didn't understand what exactly will be in `Path` and `Path\Element`

**Comment by sebastianfeldmann** [comment]
What we need is the logic if a path has placeholders and on which positions it has them.
Determine the longest static path that is save to “cd” in.
Get directory/path elements at certain positions/path depth.
You can look at the stuff I edited in Target in order to fix the local collector yesterday.

Target has currently some functionality we need, but using Target feels wrong because the “remote target” is somewhat different.

So the idea was to extract the behavior we need ;)

**Comment by vitalybaev** [comment]
I thought about extracting all path methods and properties in Target to new trait.
This is allow us don’t change much code and fit help to reach our goal, I guess.
But when to use it is a question: just in the collector that is very easy but struggling with correctness of this way, or in the new remote target collector class, that won’t do any new work
Or maybe I just think badly today )

**Comment by sebastianfeldmann** [comment]
Only two remaining.
I see light at the end of the tunnel ;)

**Comment by sebastianfeldmann** [comment]
Looks like it ;)
