### ISSUE TITLE
Composer installation not possible with Symfony 4

### ISSUE THREAD

**Issue by TheCelavi** [sebastianfeldmann/phpbu#147]
There are version conflicts between this library and some of the dependencies in Symfony 4 project, so installation by using Composer is not possible.

**Comment by sebastianfeldmann** [comment]
I think this is the problem
"symfony/event-dispatcher": "~2.6|~3.0"

I'll check if there where some incompatible changes in 4.0 and try to upgrade to to version 4.0

**Comment by sebastianfeldmann** [comment]
It should be fixed in dev-master
You may want to verify that ;)

It should be released with version 5.1 soonish ;)

**Comment by TheCelavi** [comment]
Yep, this solves it, thank you!

No reason for not bumping version up, symfony/event-dispatcher do not have BC breaks (AFAIK) migrating from 3.0 to 4.0. Symfony has this policy to bump everything up with changing major version of FW, even though most of the components are unchanged.

I think that this issue is safe to close.
