### ISSUE TITLE
Error: cant find local PATH variable

### ISSUE THREAD

**Issue by andrelopez** [sebastianfeldmann/phpbu#148]
Hi Sebastian,

Hope all is well. I got this error: "cant find local PATH variable"

I noticed that the error is from the Cli class (https://github.com/sebastianfeldmann/phpbu/blob/a95984ed50d89dc04f2aaa66022fd4c237ff918d/src/Util/Cli.php) line 182

It looks like $_SERVER('PATH') is not set in my environment. I did some research but haven't had look of how to add PATH to be read by PHP.

Just curious about what is the difference between $_SERVER['PATH'] and getenv("PATH") ?

Do you think the Exception is required? what about if the user has added custom paths to executables?

Best,
-Andre

**Comment by sebastianfeldmann** [comment]
Hi Andre

Are you sure you have the required binaries installed? If you want to backup a MySQL database ‘mysqldump’ must be installed.

There should be no difference between getenv and $_SERVER.

The PATH environment variable is needed to find your local binaries like ‘tar’ or ‘mysqldump’.

Normally it is passed to php by the system environment from the user executing php.

So on a Linux shell you could run
    ~# echo $path
and it should output something like
    /usr/bin:/usr/local/bin...
or on Windows
    : echo %PATH%
    C:\Windows;C:Windows\System32...

These are the directories the system will search if you execute a command without a path.
    ~# mysqldump ...
The shell will try to find the ‘mysqldump’ binary in all directories listed in your path.
Same goes for phpbu, it looks in every directory, trying to find the needed binaries.

You can prevent phpbu from looking by itself by providing the ‘pathTo*’ option so phpbu will know where the binary is located.

But that makes config files heavily bound to a specific environment, so I would not recommend doing so.

Best way would be to pass the right path to php via environment.

Hope that helps a bit

Cheers, Sebastian

**Comment by andrelopez** [comment]
Hi Sebastian,

Thank you for the clarification, I was able to pass the Path to PHP with an environment file in my php framework, so is working now :)

Thanks for your help.

Best
