### ISSUE TITLE
documentation for offsite backups

### ISSUE THREAD

**Issue by DanielRuf** [sebastianfeldmann/phpbu#150]
It would be useful for others to have some information how they can create offsite backups without storing the configuration anywhere (at least not on the server).

At least I miss some best practice information ;-)

**Comment by sebastianfeldmann** [comment]
The way I understand offsite backup, an offsite backup would be to `sync` (to use phpbu terminology) your backup to an "offsite" like Amazon S3, or Dropbox, away from your "normal" infrastructure.

What do you mean by not storing the configuration?
Not storing the offsite credentials within the config file?

I'm thankful for any suggestion to improve the documentation ;)

Maybe you can elaborate a bit on what you mean by best practices.

**Comment by DanielRuf** [comment]
Best practices: do not use a normal webserver to store backups (sync to local and then delete+overwrite from remote).

Ask for missing credentials to lower the attack surface when the configuration gets leaked.

Recommended setup (ssh, tls, remote - local, ...).

Had some more recommendations in my mind.

**Comment by planetahuevo** [comment]
How can you store the config file outside of the server?

**Comment by DanielRuf** [comment]
Closing as this might be out of scope and there is probably not much interest / need of other users.
