### ISSUE TITLE
feature: signed archives (hmac)

### ISSUE THREAD

**Issue by DanielRuf** [sebastianfeldmann/phpbu#152]
It would be useful to add hmac support so we can get totally signed archives, can create some audit trail or check the hashed signatures and ensure untampered backups and provide a higher assurance about the correctness (makes sense for clients who have to check the signature eg of archived releases of a project, otherwise we would need another PGP layer).

**Comment by sebastianfeldmann** [comment]
Please correct me if I'm wrong.
We would have to store an aditional signature file then, right?

    backup  => foo.tar.gz
    encrypt => foo.tar.gz.enc
    sign    => foo.tar.gz.sig

delete `foo.tar.gz` and keep `foo.tar.gz.enc` and `foo.tar.gz.sig` or is there a way to make the signature part of the encrypted file itself?

**Comment by DanielRuf** [comment]
A signature is often appended to the file (see PGP) because it is part of the file (MAC then encrypt).

Or can be in a separate file (encrypt then HMAC).

**Comment by DanielRuf** [comment]
Changed the title accordingly because we have at least these two ways when we need HMAC.
