### ISSUE TITLE
security: warn when a weak / insecure algorithm is used

### ISSUE THREAD

**Issue by DanielRuf** [sebastianfeldmann/phpbu#153]
I see in the Crypter class that it accepts all algorithms, even (insecure) stream ciphers, ecb mode ciphers and a few others.

I would like to see some warning when one of them is used ;-)

Scott of Paragonie and others block these and enforce a strong and secure algorithm.

**Comment by sebastianfeldmann** [comment]
Do you have a link to a list of those "insecure" algorithms?
Emitting a warning is or even failing sounds like a good idea.

Maybe adding a `force` option if someone is required to use one of those for some reason.

**Comment by sebastianfeldmann** [comment]
Thanks that helps a lot

**Comment by DanielRuf** [comment]
Ah seems OWASP has changed the URL.

https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html
