### ISSUE TITLE
feature request: support SSS

### ISSUE THREAD

**Issue by DanielRuf** [sebastianfeldmann/phpbu#154]
We could generate derived partial keys using Shamirs Secret Sharing to protect credentials and other values and ask for the missing key parts when needed.

Like Hashicorp Vault already does it in-memory.

**Comment by sebastianfeldmann** [comment]
My head hurts already ;)

So at some point the server executing the backup has to have access to the credentials needed to connect to services or to encrypt the backup.

How would something you suggest look like? 
Where would which part of a shared secret be stored?

**Comment by DanielRuf** [comment]
There could be multiple scenarios:
* manually enter one of the shared keys to unlock the backup process
* place one or multiple of the shared keys in a specific directory which is protected and deleted afterwards
* some configured cronjob
* (have to think about further ways that would work with phpbu)

In general this ensures that at least x authorized persons started the backup process.
This also protects the other credentials which are far more worth.

https://www.vaultproject.io/docs/concepts/seal.html described a bit how Hashicorp uses it (the daemon runs in the background and stores the shared secret in the memory)

(and I miss PGP by default)
