### ISSUE TITLE
Sync backup to Amazon S3

### ISSUE THREAD

**Issue by lushndm** [sebastianfeldmann/phpbu#157]
Hi!
Sync backup to Amazon S3 is interrupted with message: 
"'InvalidArgumentException' with message 'File not found: phar:///usr/local/bin/phpbu/lib/aws-sdk/Endpoint/../data/endpoints_prefix_history.json'
in phar:///usr/local/bin/phpbu/lib/aws-sdk/functions.php:149"

**Comment by sebastianfeldmann** [comment]
oO

**Comment by sebastianfeldmann** [comment]
Will fix it directly

**Comment by sebastianfeldmann** [comment]
Please update to version 5.1.4

The missing file should be there.
Sorry and thanks again for reporting this

**Comment by sebastianfeldmann** [comment]
Can you please confirm that version 5.1.4 is working?
For me the AWS sync is working again.
If you confirm the fix I will close this issue.
