### ISSUE TITLE
Error with ending tag for options and adapters

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#158]
Not sure why is this happening. 
On the docs: 
http://phpbu.de/manual/current/en/configuration.html#configuration.adapters
`<adapters>
    <adapter type="dotenv" name="environment">
      <option name="file" value=".env">
    </adapter>
  <adapters>
 `
But when trying I get an error if I do not add the closing tag for option
`   </option>`

Not sure why that is needed and nowhere else is.

**Comment by sebastianfeldmann** [comment]
```xml
  <adapter type="dotenv" name="environment">
    <option name="file" value=".env" />
  </adapter>
```

The closing `/`is missing in the example

**Comment by sebastianfeldmann** [comment]
I've updated the docs.

Thanks for reporting this issue ;)

**Comment by planetahuevo** [comment]
Oh,  I didn´t see that. 
There is also a / missing on the closing of <adapters>
:)
