### ISSUE TITLE
Cannot find config file

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#159]
I am trying to setup a config file for adapters

I am getting this error: 

phpbu 5.1.4 by Sebastian Feldmann and contributors.

config file not found

My config file looks like this: 

```
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/5.1/phpbu.xsd">
    <adapters>
        <adapter type="array" name="environment">
            <option name="file" value="/XXX/xxx/xxxx/backup-config.php">
                </option>
 
        </adapter>
    </adapters>
```

The file was working before I added the adapters and updated from 5.012 to 5.1.4

**Comment by sebastianfeldmann** [comment]
Invalid config path refers to an none existing array structure.

If you use

    adapter:environment:foo.bar

Your php array should look like this

```php
<?php
return [
    'foo' => [
        'bar' => 'value'
    ]
];

**Comment by planetahuevo** [comment]
Ok, I was using an incomplete array for testing.
Fixed and working!
Thanks!
