### ISSUE TITLE
Is usage only via CLI ?

### ISSUE THREAD

**Issue by collizo4sky** [sebastianfeldmann/phpbu#162]
I haven't read the doc thoroughly but is it possible to use phpbu by say instantiating a class or calling a function or anyway but without having to use the command line?

**Comment by vitalybaev** [comment]
Sure! Please take a look at `src/Runner.php`. The approximate way to run it is:
```php
// Create config instance, set file path to phpbu config file
$configuration = new \phpbu\App\Configuration();
$configuration->setFilename('../path/to/phpbu/config.json');

// Create factory instance (containing classmap of tools and stuff for bootstrapping it)
$factory = new \phpbu\App\Factory();

// Create runner
$runner = new \phpbu\App\Runner($factory);

// Execute
$runner->run($configuration);
```

But maybe I'm wrong in some steps so waiting for @sebastianfeldmann response.

**Comment by sebastianfeldmann** [comment]
No reason to wait ;)
That's exactly how its done. Thanks @vitalybaev 

If you execute `phpbu` via another php script make sure you add a default listener to handle your output, you may don't want to use the default cli printer.
This is normally done via the CLI handler, if you create it manually no default `Printer`/ `Logger` is added.

How to implement your own printer have a look at the `phpbu-laravel` package https://github.com/sebastianfeldmann/phpbu-laravel/blob/master/src/Cmd/Printer.php

It might be a nice new feature idea to add a basic html result printer.

**Comment by collizo4sky** [comment]
Thanks you both.
