### ISSUE TITLE
Encryption question

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#163]
I am testing the encryption and I cannot find this answer on the docs. 

I understand that the encryption happen after the backup creation and before the sync. 
If I decided to keep a copy on local using cleanup of 1, 
will that copy be encrypted or not? 
In case is not, is it possible to get an option to keep the unencripted data on local on cleanup even if we are syncing the encrypted copy?

Thanks!

**Comment by sebastianfeldmann** [comment]
There is an option `keepUncryptedFile` that defaults to `false`.
But remember, if you keep the unencrypted file, it will never be cleaned up.
Because `phpbu` doesn't really know about this intermediate state of your backup.
The only thing that exists for `phpbu` is the encrypted file, that will get synced and cleaned up.

**Comment by planetahuevo** [comment]
But it will be overwritten when creating a new backup? 
I am using the same name all the time (no date or time). 

If that is the case, it will work for me, as I only leave one copy behind. :)

**Comment by sebastianfeldmann** [comment]
Yes, if you are using the same file name then it will be overwritten with the next backup.
If you are using placeholders in your directory or file name then it will fill up your local storage.

**Comment by planetahuevo** [comment]
I think that works fantastic for me. 
Local backup is indeed overwritten, so I keep one local copy for easy and fast recovery and my encrypted copy on the remote server for security.
So I am closing this. :) 
Thank you for your help!
