### ISSUE TITLE
Logging per SMTP Default Port  

### ISSUE THREAD

**Issue by speedball73** [sebastianfeldmann/phpbu#164]
Hi,

based on the documentation the default port for smtp logs is 587 but it is actually port 25 (Mail.php - line 333)

**Comment by sebastianfeldmann** [comment]
Thanks, I’ll check where the error is and fix one of the two ;)

**Comment by sebastianfeldmann** [comment]
I changed the default documentation to 25, because by default encryptions is deactivated.
Maybe that should be changed in a future version. To adopt more secure default values.

Thanks for bringing this issue to my attention ;)
