### ISSUE TITLE
Release 2.0.1

### ISSUE THREAD

**Issue by F21** [sebastianfeldmann/phpbu#17]
After #15 and #16 are merged, can you release 2.0.1 and build a phar? I think the changes we have made warrant a release :smile:

**Comment by sebastianfeldmann** [comment]
Ideed!!!

**Comment by sebastianfeldmann** [comment]
:boom: Version 2.0.1 is out!
Changelog is updated.

Thank you very much for the support.

**Comment by F21** [comment]
:dancer:

**Comment by sebastianfeldmann** [comment]
PHAR is updated as well
You can give it a go with
```
phpbu.phar --self-update
```
:tada:

**Comment by F21** [comment]
Perfect! Thanks! :smile:
