### ISSUE TITLE
Any web UI?

### ISSUE THREAD

**Issue by sultanboss** [sebastianfeldmann/phpbu#171]
Is there any recommended integrated web UI to manage?

**Comment by sebastianfeldmann** [comment]
There is no web UI to manage `phpbu`. What exactly are you looking for?
In theory you only have to manage a `xml` or `json` file.

I would be open to any suggestions though.

**Comment by sultanboss** [comment]
I am talking about something like `elkarbackup` with frontend web user interface to manage/create/clone backups but using `phpbb` backend technology. More clearly, a PHP or Python based web user interface which runs in apache or nginx web server.

Thanks!

**Comment by sebastianfeldmann** [comment]
Sadly currently there is no such thing :/
