### ISSUE TITLE
S3 Encryption 

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#172]
Hi, 
I would like to ask for a new feature. 
S3 provides a default encryption system, that can be activated. 
Would be possible to add an option to the encryption so it use the default S3 encryption? 

Some info about it: 

https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

Thanks!

**Comment by sebastianfeldmann** [comment]
Have to check if the AWS Lib is supporting this, but if so, this should be doable

**Comment by planetahuevo** [comment]
I have activated it on the S3 side so it does work without any further setting on your side. No need for this anymore. :)
