### ISSUE TITLE
5.1 releases require ext-ftp

### ISSUE THREAD

**Issue by bytestream** [sebastianfeldmann/phpbu#176]
This is perhaps a docs issue but if you install via composer then it requires ext-ftp, should probably be a `suggest` if you want to use the FTP component?

```
Problem 1
    - Installation request for sebastianfeldmann/ftp 0.9.2 -> satisfiable by sebastianfeldmann/ftp[0.9.2].
    - sebastianfeldmann/ftp 0.9.2 requires ext-ftp * -> the requested PHP extension ftp is missing from your system.
  Problem 2
    - sebastianfeldmann/ftp 0.9.2 requires ext-ftp * -> the requested PHP extension ftp is missing from your system.
    - phpbu/phpbu 5.1.9 requires sebastianfeldmann/ftp ~0.9 -> satisfiable by sebastianfeldmann/ftp[0.9.2].
    - Installation request for phpbu/phpbu 5.1.9 -> satisfiable by phpbu/phpbu[5.1.9].
```

**Comment by bytestream** [comment]
Issue was I installed on a machine with `ext-ftp`, pushed to git and another machine didn't have `ext-ftp`.

So if you install on a machine with `ext-ftp` then it locks `sebastianfeldmann/ftp` to `0.9.2`, and if you install on a machine without then it locks to `0.9.1`...

**Comment by sebastianfeldmann** [comment]
I moved the `sebastianfeldmann/ftp` packed to the suggest list
Now if you don't use the ftp sync it does not get installed.
If you want to use it you have to require the lib manually.

Version 5.1.10 is released with the described changes

**Comment by sebastianfeldmann** [comment]
Thanks for reporting the issue :)
