### ISSUE TITLE
Dump mysql from docker container

### ISSUE THREAD

**Issue by AxelPAL** [sebastianfeldmann/phpbu#189]
To dump from mysql in docker container you should run mysqldump command with argument **--protocol=TCP**. Example:
`mysqldump --protocol=TCP -usomeUser -p db_name > db.sql`
At your implementation (**src/Cli/Executable/Mysqldump.php**) you have no option **protocol** and because of this it is unable to use your tool when DB is run in docker container.
This case is useful when you want to make backups outside of your DB container.

**Comment by sebastianfeldmann** [comment]
Sure, will get right on it

**Comment by sebastianfeldmann** [comment]
I tagged version 5.2.6 with the new `Mysqldump` feature.
You are now able to specify the `protocol` option in your configuration
