### ISSUE TITLE
Feature Request: Emails Subject

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#192]
Hi, 
related to this one: https://github.com/sebastianfeldmann/phpbu/issues/110

And this one 
https://github.com/sebastianfeldmann/phpbu/issues/183

I would like to ask for what I think should be an easy one. 
Can we make that the Flag  [OK|WARNING|ERROR] can be extended with a [TEST] when we are doing a dryrun? or [DRYRUN]
I am now getting 2 exacly equal emails, one for the dryrun and another for the proper backup.
I would love to filter the dryruns out from my email folder.

Thanks!

**Comment by sebastianfeldmann** [comment]
Should be doable :)

**Comment by planetahuevo** [comment]
Thanks :)
