### ISSUE TITLE
Upgrade Dotenv adapter to version 3

### ISSUE THREAD

**Issue by mattsches** [sebastianfeldmann/phpbu#195]
In version 3.* of [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) the way the `Dotenv` object is instantiated was changed:

> you will need to replace any occurrences of `new Dotenv(...)` with
`Dotenv::create(...)`, since our new native constructor takes a `Loader`
instance now

`phpbu` itself _suggests_ requiring `"vlucas/phpdotenv": "Require ~2.4 to use Dotenv adapter",`, but many current projects probably require `"vlucas/phpdotenv": "^3.3"` (e.g. Laravel 5.8).

So either
* suggest `"vlucas/phpdotenv": "Require ~3.3 to use Dotenv adapter",` and update https://github.com/sebastianfeldmann/phpbu/blob/35db2256a93339d562acdddae894b836d6ebd71f/src/Adapter/Dotenv.php#L46
* or create a new `Dotenv3` adapter

I'd prefer the first solution, but will volunteer to provide a PR for any of them. What do you think?

**Comment by mattsches** [comment]
Come to think of it, another, more unobtrusive option would be to simply check for the existence of the `create()` method in `Dotenv`, like so:

```
if (method_exists(DotenvLib::class, 'create')) {
    $this->dotenv = DotenvLib::create(dirname($this->file), basename($this->file));
} else {
    $this->dotenv = new DotenvLib(dirname($this->file), basename($this->file));
}
```

**Comment by sebastianfeldmann** [comment]
Lets upgrade to `~3.0` and internally we are using `create` only
Since version 3 is still supporting php 7.0 and even lower this should even be fine for version 5.
