### ISSUE TITLE
Make Mysqldump source restorable

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianfeldmann/phpbu#202]
Make `Mysqldump` source  implement the `Restorable` interface similar to the `Tar` source.

**Comment by rhorber** [comment]
I tried to implement this. I'm not sure if it is the way you intended to do it...
PR: #212

**Comment by rhorber** [comment]
New PR: #216
The old one got unintentionally closed by pull.

**Comment by sebastianfeldmann** [comment]
Fixed by @rhorber with pull request #216

**Comment by sebastianfeldmann** [comment]
Just released version 6.0.1 with this new feature
