### ISSUE TITLE
[Question] Idrive

### ISSUE THREAD

**Issue by lenamtl** [sebastianfeldmann/phpbu#209]
Hi,

do you plan to add Idrive?

**Comment by sebastianfeldmann** [comment]
I'm not sure but I think IDrive is a backup solution on its own. I've not seen any api to upload files to their storage but I could be mistaken.

Currently there are no plans to add IDrive.

**Comment by lenamtl** [comment]
Hi @sebastianfeldmann , here is the API I'm talking about https://www.idrivesync.com/evs/web-developers-guide.htm

**Comment by sebastianfeldmann** [comment]
Oh, if there is a composer installable php client available as well I would consider adding at ;)
