### ISSUE TITLE
Skip triggers 

### ISSUE THREAD

**Issue by enovision** [sebastianfeldmann/phpbu#217]
I am using your great utility already for a couple of years, but I have found out that when using triggers only a portion of the data is in the backup because of a bug.

My question is simple, can I add an option to skip the triggers when doing a MySQL backup? 
Something like:
```
<option "skip-triggers" value="true">
```
to keep it in line with the used standard.

It would be a difference between keep on using this utility or building something myself. Now I have backups that are useless.

**Comment by sebastianfeldmann** [comment]
Just checked there is a `--skip-trigger` option for `mysqldump`.

So you here is what you would have to do.

- Add private `skipTrigger` property to `Mysqldump` source class (default false).
- Add `skipTrigger` property and method to `Mysqldump` executable class.
- Add unit tests for both.

**Comment by rhorber** [comment]
Took the liberty to implement this, see #218

**Comment by sebastianfeldmann** [comment]
Nice one ;)

**Comment by rhorber** [comment]
It is worth noting, that the new option is named `skipTriggers` :) (as the other options are also named camelCase).

**Comment by sebastianfeldmann** [comment]
Thanks for pointing this out
I updated the release notes ;)
