### ISSUE TITLE
extendedInsert

### ISSUE THREAD

**Issue by enovision** [sebastianfeldmann/phpbu#219]
I think there is an issue with the MySQL Backup and the **extendedInsert** option. 

You can put this to _true_ or _false_. Well the way it is implemented now it is not doing anything. According to the documentation:
```
-e, --extended-insert 
     Use multiple-row INSERT syntax that include several
     VALUES lists.
     (Defaults to on; use --skip-extended-insert to disable.)
```
When you set the the **extendedInsert** to "true" it is adding "-e" in the generated mysqlbackup statement (tried it with --simulate). But the default is already "-e". Which means that leaving it out or adding it doesn't change anything, while leaving it out is just taking the same default.

What it should do when you use **extendedInsert** with a value of "false" is adding :
```
--skip-extended-insert
```
to the generated mysqlbackup statement.

I have done a test, with the above option instead of with and without the generated "-e", because I had records missing in my final backup (even after the **skipTriggers** with value "true"). The result was a larger _sql_ file, but all the records were there.

So in brief:
when:
```
<option name="extendedInsert" value="false" />
```
then:
```
--skip-extended-insert
```
should be added to the generated mysqlbackup statement.

**Comment by sebastianfeldmann** [comment]
You are absolutely right! Getting right on it ;)

**Comment by sebastianfeldmann** [comment]
I just released version 6.0.2 which now ignores the `extendedInserts` option. You can now use the new `skipExtendedInserts` option to disable extended inserts.

**Comment by enovision** [comment]
> skipExtendedInserts

That is skipExtendedInsert

Thank you very much.

**Comment by sebastianfeldmann** [comment]
Fixed it so we don't confuse anybody ;)
Thanks
