### ISSUE TITLE
Cleanup stepwise Configuration Help

### ISSUE THREAD

**Issue by Leboubou111** [sebastianfeldmann/phpbu#225]
It's really a good utility. Thanks for that :+1: 

So, I need help with the Cleanup stepwise configuration.

I've a daily backup ans I want to keep this for :
- 2 weeks (all days)
- 1 backup per month (12 months max)

I don't understand how to configure this option.

Can you please help me ?

Thanks in advance ;-)

**Comment by sebastianfeldmann** [comment]
I think this should do the trick.
- ignore the all part.
- keep 14 days of daily ones
- skip week config
- keep 12 month of monthly backups
- ignore yearly backups 

```xml
<cleanup type="stepwise">
  <option name="daysToKeepAll" value="0" />
  <option name="daysToKeepDaily" value="14" />
  <option name="weeksToKeepWeekly" value="0" />
  <option name="monthToKeepMonthly" value="12" />
  <option name="yearsToKeepYearly" value="0" />
</cleanup>
```

**Comment by Leboubou111** [comment]
Ok, it's simple finally. 
Many thanks for your help sebastian.

**Comment by sebastianfeldmann** [comment]
You are welcome, great it’s useful to you.
If you have any further questions don’t hesitate to ask.
