### ISSUE TITLE
JSON Webhook With Discord Issues

### ISSUE THREAD

**Issue by UpperCenter** [sebastianfeldmann/phpbu#227]
Hi

I'm attempting to use PHPBU to backup a MongoDB database with a Discord chat web hook.
I have a complete config file, and I believe that the config and syntax is correct.

I am using PHP Version 7.3.13 on Fedora Server 31
My PHPBU version is 6.0.3

I am running with the command: `phpbu --configuration=phpbu.json --simulate`
This is the error output given:
```sh
phpbu 6.0.3 by Sebastian Feldmann and contributors.

no uri given
```

Below is a redacted version of my complete `phpbu.json` file:
```json
{
  "verbose": true,
  "logging": [
    {
      "type": "webhook",
      "options": {
        "transport": "uri",
        "recipients": "https://discordapp.com/api/webhooks/***",
        "method": "post"
      }
    }
  ],
  "backups": [
    {
      "name": "Backup",
      "source": {
        "type": "mongodump",
        "options": {
          "databases": "***",
          "user": "***",
          "password": "***"
        }
      },
      "target": {
        "dirname": "backups",
        "filename": "MongoDBackup-%Y%m%d-%H%i",
        "compress": "bzip2"
      },
      "syncs": [
        {
          "type": "dropbox",
          "options": {
            "token": "***",
            "path": "/MongoDB-Backups-2"
          }
        }
      ],
      "cleanup": {
        "type": "Capacity",
        "options": {
          "size": "1536MB"
        }
      }
    }
  ]
}
```
Am I missing something? Are Discord webhooks not supported?

Thanks for your time.

EDIT: If more information on Discord webhooks is required, their developer documentation explains it  here [Discord Webhook Documentation ](https://discordapp.com/developers/docs/resources/webhook)

**Comment by sebastianfeldmann** [comment]
The `uri` option is missing, the following should suffice.

```json
{
  "type": "webhook",
  "options": {
    "uri": "https://discordapp.com/api/webhooks/***"
  }
}
```

You can find some more information in the [web hook documentation](https://phpbu.de/manual/current/en/logging.html#logging.webhook).

Here you will find the default request body etc. etc.

If you have further questions don't hesitate to ask ;)

**Comment by UpperCenter** [comment]
That seems to have fixed it! Apologies for that.

The webhook element still appears to be having communication issues with Discord, the output of a `--simulate` run is as follows:

```sh
PHP Warning:  file_get_contents(https://discordapp.com/api/webhooks/LegitWebhookTokenHere): failed to open stream: HTTP request failed! HTTP/1.1 400 BAD REQUEST
 in phar:///usr/local/bin/phpbu/Log/Webhook.php on line 230
Time: 1 second, Memory: 4.00MB
```

Any ideas?
Thanks again for the support.

**Comment by sebastianfeldmann** [comment]
The 400 BAD REQUEST indicates that `Discord` can't handle the given data in the request.

Out of the box `phpbu` supports 3 request body formats `form-data`, `json` and `xml`.
But the data is presented in a `phpbu` specific format. I would think that a web hook interface of any other system like `discord` would not understand that format out of the box.

As you can see in this [video](https://www.youtube.com/watch?v=IVby2exqn1w) `Discord` requires a json field `content`.

With templates you can define the request body that is send to the web hook. So you can format that data in a way `discord` requires them. But the options to customize the request body are somewhat limited, so it can be the case that you have to write a web hook bridge to make it work.

A bridge would work like this. Write a script that is callable vie URI that understands the `phpbu` data and configure its URI in the `phpbu` configuration. In that script process the data submitted and create a new request that is exactly how `discord` needs the data and authentication to be and call the `discord` web hook from your script.

Try this configuration before writing a bridge.
After scamming through the video I think this should work.


Log configuration
```
{
  "type": "webhook",
  "options": {
    "uri": "https://discordapp.com/api/webhooks/***",
    "contentType": "application/json",
    "template": "discord.json"
  }
}
```

Create the file `discord.json` with this content.

```
{"content": "Backup done: %status% - %timestamp%"}
```

**Comment by UpperCenter** [comment]
A perfect avatar! :p 

Doesn't appear to have changed anything, still getting that 400 error with a ``--simulate`` run.

Thanks for your help!

**Comment by UpperCenter** [comment]
Starting the bridge, got this so far. Semi new to PHP so apologies ;p
```php
<?php

$webhookurl = "https://discordapp.com/api/webhooks/***";

$msg = "i am above the law";

$json_data = array ('content'=>"$msg");
$make_json = json_encode($json_data);
$crl_int = curl_init( $webhookurl );
curl_setopt( $crl_int, CURLOPT_HTTPHEADER, array('Content-type: application/json'));
curl_setopt( $crl_int, CURLOPT_POST, 1);
curl_setopt( $crl_int, CURLOPT_POSTFIELDS, $make_json);
curl_setopt( $crl_int, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt( $crl_int, CURLOPT_HEADER, 0);
curl_setopt( $crl_int, CURLOPT_RETURNTRANSFER, 1);
$response = curl_exec( $crl_int );

//Debug
echo $response;
?>
```

**Comment by sebastianfeldmann** [comment]
Uhh sorry the default method is "get" so you have to change it to "post".

```
{
  "type": "webhook",
  "options": {
    "uri": "https://discordapp.com/api/webhooks/***",
    "contentType": "application/json",
    "method": "POST",
    "template": "discord.json"
  }
}
```

Hope this fixes your issue.


To your script: If you run

    php your-script-name.php

it should already send a message to the hook and work (I would guess :).

**Comment by UpperCenter** [comment]
It's working now! Thanks a lot for your help on this.

I shall just use the script for other things :p

**Comment by sebastianfeldmann** [comment]
Nice! 
You are welcome :)
