### ISSUE TITLE
[Question] backup directories on  remote server 

### ISSUE THREAD

**Issue by Liuzhj** [sebastianfeldmann/phpbu#231]
phpbu can backup directories on remote server now?

**Comment by sebastianfeldmann** [comment]
You can, by using the `rsync` source.

Have a look at the example configuration here
https://github.com/sebastianfeldmann/phpbu/blob/master/doc/config/source/rsync.xml

**Comment by Liuzhj** [comment]
thank you very much  @sebastianfeldmann 

close issue now.
