### ISSUE TITLE
OpenSSL Builtins Question

### ISSUE THREAD

**Issue by moebrowne** [sebastianfeldmann/phpbu#236]
Is there a reason we aren't using PHPs builtin functions for OpenSSL operations?

**Comment by sebastianfeldmann** [comment]
Not necessarily no. At what are you looking in particular?

**Comment by moebrowne** [comment]
I was looking at #153 and wondering if there was a way of getting supported ciphers programmatically so the list would be tailored to what your system supports rather than having a hardcoded list and came across [`openssl_get_cipher_methods()`](https://www.php.net/manual/en/function.openssl-get-cipher-methods.php)

This made we wonder if using the openssl binary was a deliberate choice

**Comment by moebrowne** [comment]
I'm going to close this as it has answered my question
