### ISSUE TITLE
PHP 7.4 Feature Usage

### ISSUE THREAD

**Issue by moebrowne** [sebastianfeldmann/phpbu#241]
The RSync location class is throwing exceptions in the `__toString` method but this is only available in PHP 7.4 (see [RFC](https://wiki.php.net/rfc/tostring_exceptions), should this be removed/replaced or should the version minimum be bumped to 7.4?

https://github.com/sebastianfeldmann/phpbu/blob/master/src/Cli/Executable/Rsync/Location.php#L96

**Comment by sebastianfeldmann** [comment]
Oh you are right, no the exception should be removed then to keep at least all currently supported versions
