### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by moebrowne** [sebastianfeldmann/phpbu#249]
What is the policy with regards to new releases?

**Comment by sebastianfeldmann** [comment]
My current plan is to merge the week cipher pull request and then release a new version ;)

**Comment by moebrowne** [comment]
Brilliant, sounds good :smiley:

**Comment by sebastianfeldmann** [comment]
I just released version 6.0.6 with all of your so far merged pull requests :)
Thanks you very much for al the work you have put into this.
