### ISSUE TITLE
Request for .phar for v6.0.7

### ISSUE THREAD

**Issue by petecooper** [sebastianfeldmann/phpbu#252]
https://github.com/sebastianfeldmann/phpbu/releases/tag/6.0.7

![Screenshot 2020-06-09 at 17 24 33](https://user-images.githubusercontent.com/226578/84174240-42b14c80-aa76-11ea-9eff-0bca4c1b87bd.png)

At the current time, v6.0.7 release has source code but not a compiled .phar file. Is there a plan to add this to the release files? Thank you.

**Comment by sebastianfeldmann** [comment]
Big UPS! 

I uploaded the PHAR to the 6.0.7 release on github.
The PHAR at https://phar.phpbu.de was updates though :)

You can run `phpbu --self-update` and it will fetch the latest release from there.

Sorry again.
