### ISSUE TITLE
Support for S3 compatible services?

### ISSUE THREAD

**Issue by gregfr** [sebastianfeldmann/phpbu#253]
Greetings
Is there a way to use PHPBU with a S3 compatible service, such as Scaleway's?
Thanks

**Comment by sebastianfeldmann** [comment]
Not out of the box. But if there is a PHP client implementation the integration into `phpbu` is not that complicated.
You can do it yourself by having a look at existing `Sync` implementations and build your own plugin accordingly or maybe create a pull request with your implementation ;)

**Comment by sebastianfeldmann** [comment]
There is an example implementation for Backblaze a S3 compatible service. You can have a look at it and create your own sync implementation based on that.
https://github.com/sebastianfeldmann/phpbu/blob/main/src/Backup/Sync/BackblazeS3.php
