### ISSUE TITLE
Best way to permit more memory to be used

### ISSUE THREAD

**Issue by petecooper** [sebastianfeldmann/phpbu#254]
I'm using PHP 7.3 and I have set `memory_limit` to `1024M`:

```
$ php73 -i | grep memory_limit
memory_limit => 1024M => 1024M
```

A vanilla backup of a Percona (MySQL) database with .xz archive format takes around 4 minutes 30 seconds, but is pegged at 4MB of memory:

```
$ sudo /usr/local/bin/php73 /etc/phpbu/phpbu.phar --configuration=/var/www/[…]/phpbu-config-daily.xml
phpbu 6.0.4 by Sebastian Feldmann and contributors.

Time: 4 minutes 36 seconds, Memory: 4.00MB

OK (2 backups, 0 checks, 0 crypts, 0 syncs, 2 cleanups)
```
If I force PHP to use more RAM at the command line (i.e. `sudo /usr/local/bin/php73 -d memory_limit=1024M /etc/phpbu/phpbu.phar --configuration=[…]`, it is still pegged at 4MB.

What is the best/preferred way to give PHPBU more RAM, please?

**Comment by sebastianfeldmann** [comment]
Persona is executed via a system call, so the memory allocated by `xtrbackup` are not shown in the PHP process, if you can define the memory limit for `xtrabackup` via command line we have to add an `option` for it.
But if you just worry that `xtrabackup` is not using the memory don't worry. You can check bei running a `top` or `htop` in another shell to actually see the `xtrabackup` process and monitor its memory, cpu and IO stats.

**Comment by petecooper** [comment]
Perfect. Thank you.
