### ISSUE TITLE
Mysqldump error: "Illegal use of option --ignore-table=<database>.<table>"

### ISSUE THREAD

**Issue by gregfr** [sebastianfeldmann/phpbu#255]
Greetings
I'm trying to use the "ignore tables" option for mysql but I have this message:

```Exception 'RuntimeException' with message 'Command failed:
  exit-code: 1
  message:   Illegal use of option --ignore-table=<database>.<table>
```

What am I doing wrong?

Thanks in advance

phpbu version 6.0.8
10.1.44-MariaDB-0+deb9u1 on Debian 9.11

**Comment by sebastianfeldmann** [comment]
Which mysqldump version are you using?

`mysqldump --version`

Maybe there is an escaping issue. Could you post your `mysqldump` configuration (without any sensitive data ;)

**Comment by gregfr** [comment]
Thanks for you answer. I'm using the defaults for my Ubuntu 19:

```
mysqldump  Ver 8.0.20-0ubuntu0.19.10.1 for Linux on x86_64 ((Ubuntu))

[mysqldump]
quick
quote-names
max_allowed_packet	= 16M
```

**Comment by sebastianfeldmann** [comment]
Thanks for the information. Could your please share your `phpbu` `<source type="mysqldump">` configuration without any passwords as well?

**Comment by sebastianfeldmann** [comment]
Maybe you where using the wrong delimiter inside your "ignoreTables" configuration.
If you still have this error feel free to reopen this issue and please provide your `xml` or `json` configuration.
