### ISSUE TITLE
Feature Request: Wasabi backup

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#256]
Hi, 
I am not sure if this is required, as Wasabi is compatible with S3 but I imagine that the endpoint will need to be updated to work. 

So, it could be nice to have and should not be really difficult to make.

What do you think?

Thanks

**Comment by sebastianfeldmann** [comment]
Should be doable ;)

**Comment by sebastianfeldmann** [comment]
You can do this by creating a custom source that extends the existing `AmazonS3v3` sync.

You can look at the `Backblaze` example implementation here
https://github.com/sebastianfeldmann/phpbu/blob/main/src/Backup/Sync/BackblazeS3.php

**Comment by planetahuevo** [comment]
I will try but this is way out of my comfort zone... :(

**Comment by sebastianfeldmann** [comment]
If you need assistance let me know.
But I have no way of testing if it works so I don't feel very comfortable adding it myself.

**Comment by planetahuevo** [comment]
I will try. :) Thanks

**Comment by planetahuevo** [comment]
@sebastianfeldmann I sent you an email about this. Can you tell me if you have received it? 
I use you contact form from your website.
Thanks!

**Comment by planetahuevo** [comment]
When do you think you can add this to the release? Thanks
