### ISSUE TITLE
Installation or usage without shell access

### ISSUE THREAD

**Issue by fredvik** [sebastianfeldmann/phpbu#257]
The documentation states that phpbu requires shell access. It would of course be very valuable to be able to run it also on shared hosting without ssh access and I cannot find any competent alternatives that are still maintained.

Can phpbu be used without shell access? I.e. are there technical limitations in the code or is it rather practical limitations of the distribution method? Are there workarounds that can be used to provide the command line interface or unpack the phar to a directory?
If phpbu can not reasonably be used without terminal/ssh access, please update the installation section of the docs to clarify it. The current wording "he easiest way to install PHPBU is to download a PHP Archive (PHAR) ..." indicates that there are other methods that works even if I cannot use phar.

**Comment by planetahuevo** [comment]
I think the other methods do not include the Phar but do include SSH, for example Composer or laravel, from the same page on the docs: http://phpbu.de/manual/6.0/en/installation.html
I do not think this will work without the command line, because that is what you will use to run it too.

**Comment by sebastianfeldmann** [comment]
Hi
so you could run `phpbu` via php.
You can write a script to execute `phpbu`. I've never tested it but I don't see a reason why it should not work.

But remember `phpbu` is just a wrapper around tools like `mysqldump`, `tar` ... and if you do not have access to those it will not work.
