### ISSUE TITLE
Invalid email formatting

### ISSUE THREAD

**Issue by seremenko** [sebastianfeldmann/phpbu#26]
There is problem with formatting of email content. 

This is what I see in command line:
<img width="397" alt="screen shot 2015-09-03 at 10 27 42 am" src="https://cloud.githubusercontent.com/assets/1233023/9661034/d1c92cb0-5226-11e5-9926-e15ead142294.png">

and this is screenshot of email content:
![screen shot 2015-09-03 at 10 27 58 am](https://cloud.githubusercontent.com/assets/1233023/9661035/d1ca154e-5226-11e5-9676-3266673f6c40.png)

**Comment by sebastianfeldmann** [comment]
Hi,
what E-Mail client do you use?

**Comment by seremenko** [comment]
gmail

**Comment by sebastianfeldmann** [comment]
The mail body in the current version is missing the whole <html> and <body> tags, maybe that's the reason. This is fixed in the master branch.

How do you use phpbu? Composer require, git clone, or PHAR?

**Comment by seremenko** [comment]
I use PHAR from http://phar.phpbu.de/phpbu.phar. Version 2.1.6

**Comment by sebastianfeldmann** [comment]
I created a new PHAR from the current `master` branch.
http://phar.phpbu.de/phpbu-2.1-dev.phar
Could you try this with your gmail account.
In my desktop and mobile clients (Apple Mail, Windows Outlook) the E-Mails look "good".

**Comment by seremenko** [comment]
This is what I see now

<img width="403" alt="screen shot 2015-09-03 at 2 09 03 pm" src="https://cloud.githubusercontent.com/assets/1233023/9666671/709f65ac-5245-11e5-9a4a-31ec4c8e9e80.png">
![screen shot 2015-09-03 at 2 09 13 pm](https://cloud.githubusercontent.com/assets/1233023/9666672/70ab407a-5245-11e5-843f-3b3197d7e2fd.png)

**Comment by sebastianfeldmann** [comment]
This is the HTML I get via E-Mail.
```
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<p>OK (1 backup, 1 check, 1 crypt, 0 syncs, 1 cleanup)</p>
<table>
  <tr>
    <td colspan="4">backup Sourcecode OK</td>
  </tr>
  <tr>
    <td></td>
    <td>executed</td>
    <td>skipped</td>
    <td>failed</td>
  </tr>
  <tr>
    <td>checks</td>
    <td style="float:right;">1</td>
    <td></td>
    <td style="float:right;">0</td>
  </tr>
  <tr>
    <td>crypts</td>
    <td style="float:right;">1</td>
    <td style="float:right;">0</td>
    <td style="float:right;">0</td>
  </tr>
  <tr>
    <td>syncs</td>
    <td style="float:right;">0</td>
    <td style="float:right;">0</td>
    <td style="float:right;">0</td>
  </tr>
  <tr>
    <td>cleanups</td>
    <td style="float:right;">1</td>
    <td style="float:right;">0</td>
    <td style="float:right;">0</td>
  </tr>
</table>
<p>Time: 554 ms, Memory: 1.50Mb</p>
</body>
</html>
```

Looks like I have to create a gmail account for further investigation ;)

**Comment by seremenko** [comment]
It seems that style="float:right;" breaks table. Check highlighted TD tag and corresponding rendered element.

![screen shot 2015-09-03 at 3 42 57 pm](https://cloud.githubusercontent.com/assets/1233023/9668966/82ecadca-5252-11e5-9efd-9e8d0fd4ec39.png)

![screen shot 2015-09-03 at 3 44 39 pm](https://cloud.githubusercontent.com/assets/1233023/9669056/f6be38f4-5252-11e5-87cc-691b45f28615.png)


Without float attribute it looks much better. Try to align to right by align="right" attribute of TD. It should work everywhere correctly.

**Comment by sebastianfeldmann** [comment]
You are so right `float:right` is just wrong.
The right style would be `text-align:right`.

I removed the style attribute and used the good old `align="right"`.

I updated the dev PHAR
http://phar.phpbu.de/phpbu-2.1-dev.phar

**Comment by seremenko** [comment]
Looks great. Thank you.

![screen shot 2015-09-03 at 4 04 17 pm](https://cloud.githubusercontent.com/assets/1233023/9669479/7abfab86-5255-11e5-91da-57eae7ddabae.png)

**Comment by sebastianfeldmann** [comment]
Thanks for your help.
I will release a new version 2.1.7 shortly
