### ISSUE TITLE
Remote FTP Cleanup throwing Exception

### ISSUE THREAD

**Issue by Sotiris-k** [sebastianfeldmann/phpbu#261]
Hello,

I'm using the remote FTP cleanup option as such

```
<sync type="ftp">
    <option name="host" value="backupServerHostHere"/>
    <option name="port" value="21"/>
    <option name="user" value="userHere"/>
    <option name="password" value="passHere"/>
    <option name="path" value="path/like/this/here"/>
    <option name="passive" value="true"/>
    <option name="cleanup.type" value="quantity"/>
    <option name="cleanup.amount" value="10"/>
</sync>
```

and I'm getting the following error

`Exception 'phpbu\App\Backup\Sync\Exception' with message 'ftp_chdir(): Invalid number of parameters' in C:\Users\Sotiris\AppData\Roaming\Composer\vendor\phpbu\phpbu\src\Backup\Sync\Ftp.php:103`

As you can see I'm using PHPBU on Windows but the FTP server is on Linux.

The files get uploaded just fine. It's just the remote cleanup that doesn't work.

Any thoughts?

**Comment by sebastianfeldmann** [comment]
The only time `ftp_chdir` is called for remote cleanups is if a file should be deleted
```php
ftp_chdir($connection, '');
```

This _should_ not be necessary, so you can try to put a `//`in front of line `53` of `vendor/phpbu/phpbu/src/Backup/File/Ftp.php` to test if this fixes your issue.

It should look like this.

```php
    /**
     * Deletes the file.
     *
     * @throws \phpbu\App\Exception
     */
    public function unlink()
    {
        try {
            //$this->ftpClient->chHome();
            $this->ftpClient->delete($this->pathname);
        } catch (\Exception $e) {
            throw new Exception($e->getMessage());
        }
    }
```

If this change fixed the issue I will make some further tests on my end and remove the `chHome` call.

**Comment by Sotiris-k** [comment]
Unfortunately this does not fix the issue. The error persists.

**Comment by sebastianfeldmann** [comment]
Are you using any dynamic path elements like /backups/%Y/%m/ or something similar?
I'm still struggling to find the actual call to `chDir` that causes the error on your side.

**Comment by Sotiris-k** [comment]
Hi @sebastianfeldmann 

Firstly, I really want to thank you for looking into this. I've been racking my brain with it for days.

My paths are all static. I've confirmed so far that it's a windows problem because with a linux stack it works fine.

Let me know if you need me to run any tests that you can think of!

**Comment by sebastianfeldmann** [comment]
No worries, happy to help if I can.
Do you have different PHP versions installed on Windows and Linux?
Because the FTP Lib has a >= PHP 7.2  hack in it.

**Comment by Sotiris-k** [comment]
On the Linux where the FTP Server is, I've no idea what they're running because it's out of my control. I don't think it matters anyway.

On the Windows side, I have PHP 7.4 installed.

**Comment by sebastianfeldmann** [comment]
Just to get this right.
You are executing `phpbu` on `Linux` and it works.
You are executing `phpbu` on `Windows` and it "crashes" with your described error.

Is that what happens?

**Comment by Sotiris-k** [comment]
Exactly.

**Comment by chland** [comment]
I've got the same problem when using phpbu on Windows 10 (PHP 7.2.31).

To see if i could figure out what's going on I wrote a small test-script that only connects to a ftp-server and then calls ftp_chdir('') - and it will always throw the exact same warning - which kinda make sense as the function expects a directory-name and an empty string is not really a valid directory-name (at least I couldn't find anything about calling CWD with an empty string to get to the home-directory).

I guess one way to fix it would be calling ftp_pwd after connecting to the remote server, store whatever path it returns as the home-directory and later use that stored value if chHome() is called.

**Comment by fra81** [comment]
hello, same problem, tried from windows 10 (php 7.3 phpbu 6.0.14) to windows 2008 Gene6 FTP server, and from linux (php 7.0 with phpbu 5.2.10) to same FTP server

error message from phpbu is the same

Exception 'phpbu\App\Backup\Sync\Exception' with message ''
phpbu/phpbu.phar/Backup/Sync/Ftp.php:103 or phpbu.phar/Backup/Sync/Ftp.php:104

I could debug from server side log, I see in the case of windows phpbu 6.0.14 after the STOR (command ran ok), the command MLSD to retrieve the remote list of files (as I understand) from my configured remote folder diablo2.test, but return 550

![image](https://user-images.githubusercontent.com/15064492/108130489-0b3c7a80-70b0-11eb-8b0f-e413de304905.png)

and for linux case I see the command NLST

![image](https://user-images.githubusercontent.com/15064492/108130467-01b31280-70b0-11eb-8731-116466e78e4b.png)

but seems no cleaner are done, as I configured amount:3 (type:quantity) and on the server there are more files present

**Comment by sebastianfeldmann** [comment]
I update the FTP implementation as @chland suggested. I now store the home directory on the initial connect and if `chHome` is called I use the previously stored value so it should not be called with the empty string anymore.

The `PHAR` is not yet updated, but I will do so ASAP.
