### ISSUE TITLE
Exclude dirs don't work as expected

### ISSUE THREAD

**Issue by andreas93j** [sebastianfeldmann/phpbu#263]
Sample structure:

- dir1
- dir2
  - data (shouldn't be excluded)
- data (should be excluded)

```xml
<source type="tar">
        <option name="path" value="../../basedir"/>
        <option name="exclude" value="data"/>
      </source>
```

Both data dirs are removed. And that's exactly what the documentation says...

BUT: How can I just remove the data dir in the basedir?

I've tried some other syntaxes but unfortunately none of them work (because phpbu just uses tar under the hood... ):
```xml
<option name="exclude" value="../../basedir/data"/>
<option name="exclude" value="./data"/>
<option name="exclude" value="''./data'"/>
```

Have you got an idea how I can solve this?

Thanks & Best wishes

**Comment by sebastianfeldmann** [comment]
Rename one of the directories ;)

But seriously, sadly the only thing `phpbu` is wrapping `tar` and if `tar` cannot do this sadly there is no way for `phpbu` to do it :/

I have to check if tar supports some special syntax to archive this.

**Comment by andreas93j** [comment]
Thx for the quick reply.

Unfortunatley renaming is not an option in this case. (nextcloud's default file structure - sometimes 3rd party apps have also data dirs and that f..funnies up the whole backup - since those are missing... and they defenitely shouldn't as a backup)

In the meantime I've checked some tar snippets which offers the option I'm looking for:
```bash
$ tar --exclude='./folder' --exclude='./upload/folder2' -zcvf /backup/filename.tgz .
```
ref: https://stackoverflow.com/questions/984204/shell-command-to-tar-directory-excluding-certain-files-folders

The following syntax produces the same --exclude flag (adapted for my case):
```xml
<option name="exclude" value="''./data'"/>
```
I've checked it via `ps -aux` and it looks the same for the tar call. But it still ignores the exclusion... and I've no clue why:

```bash
/bin/tar --exclude='./data' -jcf /home/sites/site****/web/apis/config/../data/backup/files/nextcloud-files-20200928-2136.tar.bz2 -C /home/sites/site****/web/apis/config/../.. nextcloud
```

& Liebe Grüße aus Tirol

**Comment by sebastianfeldmann** [comment]
I tried to get it to work using tar directly but I could not get it working.
I tried

```
/
  foo.md
  data/
    foo.log
  src/
    data/
      foo.md
```

I tried to exclude the `/data` dir but include the `/src/data` directory. 
But even with `./` as a prefix both directories get excluded.

The only way I could make it work was excluding `data/*.log` but this only works of you have different file types in both data directories.

So since this is not working with `tar` directly there is no way we could make this work in `phpbu` :(

**Comment by andreas93j** [comment]
Thank you so much for your support. That's really unfortunate :-(

The data dir in nextcloud includes all files which are stored in the cloud.

I think I'll just make a workaroud

backup 1

- full backup with exclusion of data dir

backup 2

- partial backup of the plugin folder (which has the data dirs - which should be in the backup)

Not perfect - but better than nothing :)

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by planetahuevo** [comment]
Have you tried using "include" combined with exclude? 
https://stackoverflow.com/questions/5747755/tar-with-include-pattern

**Comment by planetahuevo** [comment]
Hi, @sebastianfeldmann I am trying to use the include option of tar using PHPBU but I cannot make it work. 
And I realise it is not on the options http://phpbu.de/manual/current/en/source.html#source.tar.exclude 
Does phpbu allow to use tar include? 
Thanks!
