### ISSUE TITLE
Support Google Cloud Storage Sync

### ISSUE THREAD

**Issue by lcsdms** [sebastianfeldmann/phpbu#285]
Hi! First of all, thanks for the awesome library!

I've made an adapter for using Google Cloud Storage for personal use, and was wondering it would be nice to implement on the base project. How could I contribute ?

Just make up a fork then a pull Request ? 
Are there any guidelines ?

**Comment by sebastianfeldmann** [comment]
Hi, thanks. Contributing the Sync would be nice.

Basically just look at the existing syncs, try to provide some unit tests as well and the yes.
Create a fork and open a pull request :)
