### ISSUE TITLE
Update S3 docs

### ISSUE THREAD

**Issue by BenBao93** [sebastianfeldmann/phpbu#286]
The docs for [AmazonS3 Sync](https://phpbu.de/manual/current/en/sync.html#sync.amazon) state that the option "path" is not required and will be assumed with default "/". However if omitted an error is returned:
```
Exception 'phpbu\App\Backup\Sync\Exception' with message 'path is mandatory'
in src/Backup/Sync/AmazonS3.php:146
```

This seems to be because 'path' is included in the validation check call at ` src/Backup/Sync/AmazonS3.php:120`

**Comment by sebastianfeldmann** [comment]
I'll just make path optional then :)

**Comment by sebastianfeldmann** [comment]
Starting from the next release `path` with really be optional.

Thanks :)
