### ISSUE TITLE
Consider offering `phpbu.phar.gz` & `phpbu.phar.bz2` to save some bytes

### ISSUE THREAD

**Issue by petecooper** [sebastianfeldmann/phpbu#289]
First of all, thank you for making `phpbu`, it continues to be excellent.

I have inherited some very remote servers where sadly connectivity is not 100% reliable and mobile data is used as a fallback when the wired connection goes down (which is more often than I would like). One of my tasks is to reduce the amount of data received over the wire.

Would it be possible, and viable, to offer `phpbu.phar` as a compressed archive, if it isn't already? For example, using Bzip2 and / or Gzip compression to produce `phpbu.phar.bz2` and / or `phpbu.phar.gz` alongside the standard `phpbu.phar` currently offered. These options would require PHP support for Bzip2 and Gzip respectively, and this would require a note in `README.md` or similar.

Thank you for your consideration.

**Comment by sebastianfeldmann** [comment]
Hi there, so the `phpbu` phar file is already zip compressed. When I tested it unzipped a while ago it was roughly 14 MB in size The current release is about 2.1 MB in size. Since it is compressed already providing it as `phpbu.phar.zip` or `bz2` would not improve the situation much :(

**Comment by petecooper** [comment]
>so the phpbu phar file is already zip compressed

Ah, yes – you are absolutely correct – now I see it. Thank you for your time and attention, I will close the issue.
