### ISSUE TITLE
Bootstrap param ignored

### ISSUE THREAD

**Issue by thiagotalma** [sebastianfeldmann/phpbu#29]
Hello @sebastianfeldmann 
Congratulations for the great job they did here.

I'm testing running using the bootstrap but never with success.
I noticed that the file sent as a parameter is never executed.

Searching by code I saw that the method Runner::handleBootstrap() is never called. It is correct?

Cheers!

**Comment by sebastianfeldmann** [comment]
Thanks Thiago,

I fixed the problem in version 2.1.10.
If you use the PHAR release you can update to the latest version with ```phpbu --self-update```

**Comment by thiagotalma** [comment]
:+1: 

You should include testing with the bootstrap  :)

**Comment by sebastianfeldmann** [comment]
You are absolutly right, I'm trying to figure out the best way of tesring the Runner. Currently it is very hard to test, maybe some refactoring is in order :)
