### ISSUE TITLE
'tar' was nowhere to be found please specify the correct path

### ISSUE THREAD

**Issue by sakonn** [sebastianfeldmann/phpbu#291]
Hello, 
I am implementing phpbu for simple backup of website. I want to setup tar backups but I am still getting this error: 
`'tar' was nowhere to be found please specify the correct path`.

I have the simple configuration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/6.0/phpbu.xsd"
  >
  <backups>
  <backup name="WebData">
      <!-- backup source -->
      <source type="tar">
        <option name="path" value="../web"/>	
      </source>
      <!-- where should the backup be stored -->
      <target dirname="backup"
              filename="edorasdata-%Y%m%d-%H%i.tar"
              compress="bzip2"/>
      <!-- cleanup the backup location
           as soon as number of created backups
           is higher than 4 -->
      <cleanup type="quantity">
        <option name="amount" value="2"/>
      </cleanup>
    </backup>
  </backups>
</phpbu>
```

Phpbu is run by CRON on the hosting. I thought that it would be because of CRON environment but hosting company has confirmed that tar is available there. In addition to that I have tried to run tar command from different php file which works fine. 

Tar is located there at these paths: `tar: /usr/lib/tar /bin/tar /usr/include/tar.h /usr/share/man/man1/tar.1.gz`. So I have tried to pass the location manually like: `<option name="pathToTar" value="/usr/lib/tar"/>` but the result is just: `wrong path specified for 'tar': /usr/lib/tar`.

Except tar I hav problems with bzip2 compression which throws the same error. Only mysqldump works fine there.

**Comment by sebastianfeldmann** [comment]
Try to use this instead :)

```
<option name="pathToTar" value="/usr/lib"/>
```

**Comment by sakonn** [comment]
Thanks fot the answer.
I have tried all kind of combinations of specifing the location but I wasn't able to run it. Your option is throwing this error: 
`Exception 'RuntimeException' with message 'wrong path specified for 'tar': /usr/lib'
in phar:///data/7/5/753eaa3c-7396-43d2-a0bb-ff448fe2641c/tiptopauto.sk/bin/phpbu.phar/Util/Cli.php:126`

**Comment by sebastianfeldmann** [comment]
The important thing is that you only provide the directory where your command is located without `/tar`.

Then it should work if you provide the right directory where `tar` can be found and executed.

**Comment by sakonn** [comment]
I think so but I haven't found where the problem is. As, I have mentioned in the initial description when I create different php file with simple tar operation and set up CRON the same way as with phpbu.phar, it works without complications.

My solution was only to set up cron jobs through shell and not through admin interface. In shell it works without complications.

**Comment by sebastianfeldmann** [comment]
Looks like your cron jobs run with a different environment or a different shell maybe.
You can check by writing the `printenv` output to a file via cron
    printenv > /tmp/env.txt
And compare it with the output if you run it manually.
