### ISSUE TITLE
Feature Request for MYSQL dumps

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#293]
Hi, 
Would be possible to have an option to tell phpbu to read the mysql config file for the user and passwords before the dump?

The option could be something like the ansible mysql module, that allows to provide a path for the  "config_file"
Default:
"~/.my.cnf"

Will that work? 

Thanks

**Comment by sebastianfeldmann** [comment]
Sounds doable :)
We would have to an option for the .cnf file and write a regex to extract username and password from its content.

**Comment by planetahuevo** [comment]
That will simplify a lot the backups when using MYSQL. :) 
Thanks!

**Comment by sebastianfeldmann** [comment]
But if you have a `.cnf` file you only have to make sure that it is used by mysqldump.
Most of the time it is a user or path issue :)
