### ISSUE TITLE
Move phpmailer to suggests

### ISSUE THREAD

**Issue by bytestream** [sebastianfeldmann/phpbu#296]
I would like to propose that the below is moved to the composer `suggest` list https://github.com/sebastianfeldmann/phpbu/blob/81624ce079009b33cfc27105db55f21d81739077/composer.json#L53 

As far as I'm aware, https://github.com/sebastianfeldmann/phpbu/blob/main/src/Log/Mail.php is the only usage and if you don't configure it via [logging](http://phpbu.de/manual/current/en/logging.html) it's not used.

@sebastianfeldmann what do you think?

**Comment by sebastianfeldmann** [comment]
Sound like a good idea
