### ISSUE TITLE
"error reading input file", openssl error

### ISSUE THREAD

**Issue by anik1ng** [sebastianfeldmann/phpbu#301]
Hi!

I use openssl encryption for my backups, but today i try decrypt files, and get error "error reading input file".

My config:
```
<crypt type="openssl">
  <option name="certFile" value="certificate.crt"/>
  <option name="algorithm" value="aes256"/>
</crypt>
```

To generate certificate and decrypt i use instruction from documentation phpbu:
generate certificate — openssl req -x509 -new -days 100000 -key private.pem -out certificate.pem

decrypt:
```
openssl enc -d -a -aes-256-cbc \
  -in backup.tar.bz2.enc \
  -out backup.tar.bz2 \
  -pass pass:mySecretPassword
```

How i can decrypt my backups? :(

**Comment by anik1ng** [comment]
Sorry, i'm stupid :D

**Comment by sebastianfeldmann** [comment]
No you are not. Don’t worry about it encryption is hard. Sometimes even from a user perspective 😊

Glad you figured it out.
