### ISSUE TITLE
multiple files sources and databases compressed in 1 file?

### ISSUE THREAD

**Issue by A973C** [sebastianfeldmann/phpbu#302]
Hi Sebastian,

First of all, i'd like to thank you for this repo: absolutely amazing!! I'm playing with it since few hours to manage my backups. Working like a charm :)

I would like to know if it's possible to create a job (so 1 config file) with multiple files sources on the same web server, multiple databases backups and all those backups are compressed in 1 tar file?

Thank you for your help!

**Comment by sebastianfeldmann** [comment]
Hi
thanks, great that you like it.

To your question:
So all jobs within a config file are processed sequentially.
That means you could store all backups in a single directory and your last `backup` in your config file creates a `tar` of that directory.

That should work

**Comment by A973C** [comment]
Thank you very much @sebastianfeldmann 
I've revised my script regarding your answer, and now the whole and long backup process is working great!

However, I have another question: I have encrypted my global archive with openssl and password + aes-256-cbc options.
How can I decrypt my file on Windows? I have downloaded and installed openssl libraries. And when i decrypt, I have this error message:

```
bad magic number
error in aes-256-cbc
```

I guess it depends of the encryption options?

**Comment by A973C** [comment]
Here is the command line used: `openssl enc -d -a -aes-256-cbc -in test.enc -out test.bz2`

And here the output:

> enter aes-256-cbc decryption password:
> *** WARNING : deprecated key derivation used.
> Using -iter or -pbkdf2 would be better.
> bad decrypt
> 4132:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto\evp\evp_enc.c:610:
> error in enc

I'm using OpenSSL 1.1.1k  25 Mar 2021 on Windows 10.

**Comment by A973C** [comment]
Anyone know how to decrypt an archive from Windows please?

**Comment by A973C** [comment]
OK I've switched to another script. I need to manage my backups on windows too...
