### ISSUE TITLE
Incremental backup

### ISSUE THREAD

**Issue by cosmopolit** [sebastianfeldmann/phpbu#31]
Haven't found any option to backup only changed files or mysql dumps

**Comment by sebastianfeldmann** [comment]
I don't know if I understand you correctly.
Incremental file/directory backup would be a nice feature ;)
Only changed mysql dumps is the part I don't understand.

Could you give me an example and explain what you want to achieve.

**Comment by cosmopolit** [comment]
Thanks for the fast reply ! 

I mean a incremental/Differential MySQL Backup using mysqldump. You can simulate incremental backup by enabling and then backing up the binary logs. See http://dev.mysql.com/doc/refman/5.1/en/backup-methods.html under "Making Incremental Backups by Enabling the Binary Log."

Would be nice to trigger this within your xml config.

**Comment by sebastianfeldmann** [comment]
If you want wo do incremental backups for mysql I heavily recommend Percona 'XtraBackup'
I think phpbu it is not the right place to keep track if the incremental backup process.
There is a phpbu source for 'XtraBackup' but I think it doesn't support incremental backups right now.

I'll close this Issue and open a Feature Request to add the missing functionality.

**Comment by sebastianfeldmann** [comment]
Sorry forgot to add the link
https://www.percona.com/doc/percona-xtrabackup/2.1/xtrabackup_bin/incremental_backups.html

**Comment by sebastianfeldmann** [comment]
Follow up in #33
