### ISSUE TITLE
Documentation how to schedule

### ISSUE THREAD

**Issue by cosmopolit** [sebastianfeldmann/phpbu#32]
For completition and beginners, haven't found anything about scheduling, i.e. with crontab. Examples?

**Comment by sebastianfeldmann** [comment]
I'll add a cron tab example

**Comment by sebastianfeldmann** [comment]
I added a short section how to schedule the backup process with Cron
http://phpbu.de/manual/current/en/configuration.html#configuration.schedule

If you have further suggestions to enhance the documentation feel free to create pull requests ;)
The complete documentation is available on github
https://github.com/sebastianfeldmann/phpbu-documentation

Cheers, Sebastian
