### ISSUE TITLE
Debug not allowed

### ISSUE THREAD

**Issue by tebeso** [sebastianfeldmann/phpbu#323]
> phpbu 6.0.16 by Sebastian Feldmann and contributors.
> 
>   Warning - The configuration file did not pass validation!
>   The following problems have been detected:
> 
>   Line 5:
>   - Element 'phpbu', attribute 'debug': The attribute 'debug' is not allowed.
> 
> Runtime:       PHP 8.1.2
> Configuration: /root/phpbu/phpbu.xml

[Screenshot from config](https://i.ibb.co/vdbTYpX/Screenshot-from-2022-10-02-13-56-39.png)

**Comment by hype09** [comment]
It seems like support for this has not been implemented yet, although it already exists in the documentation.

I went ahead and created a [pull request](https://github.com/sebastianfeldmann/phpbu/pull/324) that should add the documented behavior.
