### ISSUE TITLE
Broken emails sent by phpbu

### ISSUE THREAD

**Issue by cccaballero** [sebastianfeldmann/phpbu#343]
I am having a problem that is the same as the one I had before when using an old version of PHPMailer in php 8.0, the metadata of the sent email is broken, because extra spaces are added in front of some metadata (the custom metadata, in the case of the problem when using old version of PHPMailer).

In the case of the old PHPMailer version was because of line terminators, that should be `\r\n` instead of `\n` as of php 8.x

Using phpbu phar 6.0.16 and PHP 8.0.x

**Comment by sebastianfeldmann** [comment]
There are currently some issues with the PHAR build, some dependencies are causing problems to fully support the 8+ versions of PHP for the PHAR.
I'm currently working on a fix :)

**Comment by sebastianfeldmann** [comment]
Full support for PHP > 8.0 and <= 8.3 is available since version 6.0.22
