### ISSUE TITLE
excludeCollections in mongodb

### ISSUE THREAD

**Issue by mdjaman** [sebastianfeldmann/phpbu#344]
Hello there is a little bug on excludeCollections mongodb executable dump.

<img width="850" alt="image" src="https://github.com/sebastianfeldmann/phpbu/assets/803262/a2e5f7fd-1f99-481a-a4e4-36980483d811">

`$cmd->addOptionIfNotEmpty('--excludeCollection', $this->excludeCollections);` 

should be as described in documentation

<img width="817" alt="image" src="https://github.com/sebastianfeldmann/phpbu/assets/803262/c30aef5b-0886-4ae5-98e8-3fc4f766e9ff">

```<?php
...
if (count($this->excludeCollections)) {
    foreach ($this->excludeCollections as $col) {
        $cmd->addOption('--excludeCollection', $col, ' ');
    }
}
```

**Comment by sebastianfeldmann** [comment]
Fixed thanks to #345 by @mdjaman

**Comment by mdjaman** [comment]
Hello @sebastianfeldmann thanks for committing it. Would u publish to new tag (6.0.20)?

**Comment by sebastianfeldmann** [comment]
Done ;)

**Comment by mdjaman** [comment]
Sorry i missed the notification 🙏
