### ISSUE TITLE
PHP 8.2.9 PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Collection" not found in phar

### ISSUE THREAD

**Issue by benjamin74** [sebastianfeldmann/phpbu#346]
Hello,

phpbu.phar downloaded from the site using wget https://phar.phpbu.de/phpbu.phar

version: phpbu 6.0.20

when trying to run it I get:

`phpbu 6.0.20 by Sebastian Feldmann and contributors.

Runtime:       PHP 8.2.9
Configuration: /root/tools/phpbu.xml

PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Collection" not found in phar:///root/tools/phpbu.phar/lib/dropbox/Models/ModelCollection.php:9
Stack trace:
#0 /root/tools/phpbu.phar(1804): require()
#1 phar:///root/tools/phpbu.phar/lib/dropbox/Models/MetadataCollection.php(148): {closure}()
#2 phar:///root/tools/phpbu.phar/lib/dropbox/Models/MetadataCollection.php(69): Kunnu\Dropbox\Models\MetadataCollection->processItems()
#3 phar:///root/tools/phpbu.phar/lib/dropbox/Models/ModelFactory.php(38): Kunnu\Dropbox\Models\MetadataCollection->__construct()
#4 phar:///root/tools/phpbu.phar/lib/dropbox/Dropbox.php(319): Kunnu\Dropbox\Models\ModelFactory::make()
#5 phar:///root/tools/phpbu.phar/lib/dropbox/Dropbox.php(348): Kunnu\Dropbox\Dropbox->makeModelFromResponse()
#6 phar:///root/tools/phpbu.phar/Backup/Collector/Dropbox.php(49): Kunnu\Dropbox\Dropbox->listFolder()
#7 phar:///root/tools/phpbu.phar/Backup/Collector/Abstraction.php(74): phpbu\App\Backup\Collector\Dropbox->collectBackups()
#8 phar:///root/tools/phpbu.phar/Backup/Cleaner/Stepwise.php(150): phpbu\App\Backup\Collector\Abstraction->getBackupFiles()
#9 phar:///root/tools/phpbu.phar/Backup/Cleaner/Abstraction.php(40): phpbu\App\Backup\Cleaner\Stepwise->getFilesToDelete()
#10 phar:///root/tools/phpbu.phar/Backup/Sync/Cleanable.php(91): phpbu\App\Backup\Cleaner\Abstraction->cleanup()
#11 phar:///root/tools/phpbu.phar/Backup/Sync/Dropbox.php(125): phpbu\App\Backup\Sync\Dropbox->cleanup()
#12 phar:///root/tools/phpbu.phar/Runner/Backup.php(205): phpbu\App\Backup\Sync\Dropbox->sync()
#13 phar:///root/tools/phpbu.phar/Runner/Backup.php(92): phpbu\App\Runner\Backup->executeSyncs()
#14 phar:///root/tools/phpbu.phar/Runner.php(59): phpbu\App\Runner\Backup->run()
#15 phar:///root/tools/phpbu.phar/Cmd.php(100): phpbu\App\Runner->run()
#16 phar:///root/tools/phpbu.phar/Cmd.php(444): phpbu\App\Cmd->run()
#17 /root/tools/phpbu.phar(1831): phpbu\App\Cmd::main()
#18 {main}
  thrown in phar:///root/tools/phpbu.phar/lib/dropbox/Models/ModelCollection.php on line 9`
  
  I don't know what is broken, I mostly adapted an old working phpbu.xml file that I had.

**Comment by sebastianfeldmann** [comment]
PHAR build is fixed since `6.0.20`
