### ISSUE TITLE
isDirSync not working

### ISSUE THREAD

**Issue by ohmydevops** [sebastianfeldmann/phpbu#349]
Thanks for this amazing tool.
I have a problem. When I enable isDirSync, the tar file is still created and persisted.

**Comment by sebastianfeldmann** [comment]
I will have a look at it

**Comment by ohmydevops** [comment]
Thank you sebastianfeldmann

**Comment by sebastianfeldmann** [comment]
Fixed with version `6.0.22`

**Comment by sebastianfeldmann** [comment]
If you continue to have this problem, feel free to re-open the issue at any time.

**Comment by ohmydevops** [comment]
Please update phar version
