### ISSUE TITLE
SSL decryption issue

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianfeldmann/phpbu#359]
I know almost nothing about SSL stuff like this; but is this the reason why I get this error when trying to decrypt an encrypted backup using the decrypt example in the docs?

    OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)

encoding:

```
      "crypt": {
        "type": "openssl",
        "options": {
          "password": "kkwMZ",
          "algorithm": "aes-256-cbc"
        }
      }
```

decrypt:

```
openssl enc -d -a -aes-256-cbc -in mi-2024-01-11-1455.sql.bz2.enc -out backup.tar.bz2 -pass pass:kkwMZ
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
68140000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers\implementations\ciphers\ciphercommon_block.c:112:
```

_Originally posted by @YouveGotMeowxy

**Comment by sebastianfeldmann** [comment]
@YouveGotMoewxy

Not critical but will be fixed with the next release if you set the `kexDerivation` option to `true`.

**Comment by YouveGotMeowxy** [comment]
I downloaded an old version of OpenSSL (v1-something) and the code example from the website works.
