### ISSUE TITLE
What will happen if the database is huge?

### ISSUE THREAD

**Issue by OpenSourceSimon** [sebastianfeldmann/phpbu#366]
I'm creating a logbook in my PostgreSQL database where a lot of rows will be created. Can phpbu split the back-up into multiple files? Otherwise it won't be very readable

**Comment by sebastianfeldmann** [comment]
Not sure `pgdump` supports something like that. But I would argue that the dump doesn't have be humanly readable. You should worry more about the machine readability so you can easily restore the backup.
