### ISSUE TITLE
syntax error, unexpected '|', expecting variable

### ISSUE THREAD

**Issue by mgjuhler** [sebastianfeldmann/phpbu#375]
Symfony CLI version 5.8.15

phpbu 6.0.22 by Sebastian Feldmann and contributors.

Runtime:       PHP 7.4.33
Configuration: /home/user/backup/config.xml

PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in phar:///home/user/backup/phpbu.phar/lib/symfony/process/Process.php on line 54

**Comment by sebastianfeldmann** [comment]
Minimum required PHP version is 8.0 😬

**Comment by mgjuhler** [comment]
oh.. i did not see that. Thx

Is it correct that version 6.0.21 is the latest to support php < 8.0 ?
