### ISSUE TITLE
Upgrade AWS to version 3

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianfeldmann/phpbu#38]
The Amazon AWS SDK should be upgraded to version 3.x

**Comment by barryvdh** [comment]
Why not replace all your custom Sync drivers with Flysystem: https://github.com/thephpleague/flysystem
Supports AWS, Dropbox, (S)FTP, Copy, Rackspace, Local etc. Also supports streams, so you just create an adapter and use Flysystem the same way for all.

```php
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$client = S3Client::factory([
    'credentials' => [
        'key'    => $this->key,
        'secret' => $this->secret,
    ],
    'region' => $this->region,
    'version' => 'latest',
]);

$adapter = new AwsS3Adapter($client, $this->bucket);
$filesystem = new Filesystem($adapter);

$fh = fopen($sourcePath, 'r');
$filesystem->putStream($targetPath, $fh);
```

**Comment by sebastianfeldmann** [comment]
I thought about that too, would make things a lot easier.
I hasitaded so far to keep the dependencies and the PHAR file as small as possible. But maybe it's time to do it the "easy" way.

**Comment by sebastianfeldmann** [comment]
For now I postponed the migration to `Flysystem` and added support for "pure" AWS sdk version 3.

I think I will add a generic `Flysystem` Sync in the future so you can handle all file systems supported by `Flysystem` with one Sync implementation.
