### ISSUE TITLE
need option datadir for xtrabackup

### ISSUE THREAD

**Issue by sugengsuprayogi** [sebastianfeldmann/phpbu#39]
I'm using non default datadir, i'm use /backup/mysql and then when configuration file in source section use xtrabackup

Using server version 10.1.9-MariaDB
Error: option 'datadir' has different values:
  '.' in defaults file
  '/backup/mysql/' in SHOW VARIABLES

ps : need option datadir

**Comment by sebastianfeldmann** [comment]
Hi,
I added a `dataDir` option to the xtrabackup source and released it with version 2.1.14.
Documentation can be found [here](http://phpbu.de/manual/current/en/source.html#source.xtrabackup)
Cheers, Sebastian
