### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by basyanya** [sebastianfeldmann/phpbu#4]
Hi, Sebastian!

Are you going to make your project working in Windows?

If no, I'd like to do it, because my project works both Linux and Windows and I'd like one 'backup script' in both OS.

**Comment by sebastianfeldmann** [comment]
*phpbu* makes use of a lot POSIX shell features like combining commands with `&&` and redirecting stdOut and stdErr with  `>`
I haven't tied it on Windows yet and I'am not a Windows command line expert.
But I could think of a lot that has to be changed to work with a Windows shell especially the `phpbu\App\Backup\Cli` classes.

Have you tried to run it on a Windows system?
What do you think has to be changed to work on windows as well.

**Comment by basyanya** [comment]
Yes, I tried to run _phpbu_ on Windows yesterday.

I have made a little straight code changes to make _mysqldump_ worked.
* In ```vendor/phpbu/phpbu/src/Backup/Source/Mysqldump.php``` in method **setupMysqldump**
```php
 $this->binary = Util\Cli::detectCmdLocation(
                'mysqldump.exe',                      //add .exe
                Util\Arr::getValue($conf, 'pathToMysqldump'),
                array(
                    '/usr/local/mysql/bin/mysqldump', // Mac OS X
                    '/usr/mysql/bin/mysqldump',        // Linux
	                'C:\work\xampp\mysql\bin',        // Windows path (todo: import %PATH%)
                )
            );
```
* I have added option _showStdErr_ to source section in xml config to exclude ``` 2> /dev/null ``` from command 
```
            <source type="mysqldump">
                <option name="showStdErr" value="true"/>
            </source>
```
With this changes _phpbu_ makes database dump without compress.

I don't finish my investigation because I have decided to get your opinion about windows version.

Course, the tests and decisions about tar, compress and sync options are needed.

**Comment by sebastianfeldmann** [comment]
You can use this undocumented option to specify the path to the `mysqldump` command.

    <option name="pathToMysqldump" value="C:\work\xampp\mysql\bin"/>

This leaves us with the `.exe` and the compression.

To make the current classes work on UX and Windows systems they most likely would become an **if-else-hell**

Another solution would be to register special windows `Sources` like `win-mysqldump`.
But that would mean you have to use different configurations for different systems. Not really ideal.

The best way i could think of right now would be to:
- Write a Package that would offer special *Windows-Sources* for *mysqldump* and others.
- Use a *bootstrap-file* to determine the current OS
- Overwrite the sources with your Special-OS-Implementation

bootstrap.php

```php
// autoloading of 'MyPackage' should be enabled
if (defined('PHP_WINDOWS_VERSION_BUILD')) {
    phpbu\App\Factory::register('source', 'mysqldump', '\\MyPackage\\WinBackup\\Mysqldump', true);
    // overwrite other sources if needed
}
```

All you have to do is implement the *SourceInterface* `phpbu\App\Backup\Source` with all your custom backup sources.

I will take a closer look at this tonight.

**Comment by sebastianfeldmann** [comment]
Maybe I found another solution for this.
I added the possibility to register command locations like `'C:\work\xampp\mysql\bin'`.
Use a bootstrap file

    phpbu --bootrap=bootstrap.php

That looks like this.

```php
<?php
phpbu\App\Backup\Source\Mysqldump::addCommandLocation('C:\work\xampp\mysql\bin');
```
I changed the command detection for windows systems, so it searches for '.exe' files as well.
Finaly I completely disabled the stdErr redirection `2> /dev/null` for Windows Systems.

So you should be able to use the same config for windows and linux, as long as you don't use `tar` or any other OS dependand functionality.

You can pull the `master` branch and verify if it works for you.

**Comment by basyanya** [comment]
Thanks a lot for your improvements!

I've checked two variants with _mysqldump_
* Using option with path to mysqldump in config file. 
E.g. `<option name="pathToMysqldump" value="C:\work\xampp\mysql\bin"/>`
It works perfect for me!

* Using bootstrap file from your last message. It works too, but PHP has thrown notice
`Notice: Undefined index: PATH in .....\vendor\phpbu\phpbu\src\Util\Cli.php on line 87`
On line 87 we can see 
```php
        $pathList = explode(PATH_SEPARATOR, $_SERVER['PATH']);
```
and the notice has thrown because $_SERVER['Path'] not 'PATH'.
I don't know why is it, may be in windows that's normal.

Also I have checked `compress='gzip'` in target section and it works too because I have gzip.exe in my path.
I discovered that gzip, tar and some more linux cli tools is installed with GIT under Windows.

So, I've decided to check `<source type="tar">` and get the exception `Exception 'RuntimeException' with message ''tar' was nowhere to be found please specify the correct path'
in .....\vendor\phpbu\phpbu\src\Util\Cli.php:104`

Could you add ability to point path to tar and append '.exe' to this part in the future?

**Comment by sebastianfeldmann** [comment]
i just added a method to get the $PATH Variable that checks `PATH`, `Path` and `path`so that should work now.

You can use `pathToTar` option to specifiy the directory where yout `tar.exe` is located then it should be detected.

**Comment by sebastianfeldmann** [comment]
I also moved `addCommandLocation` to the `Binary` parent class of `Mysqldump`, `Tar` and `Mongodump`. 
Now you additionally have to specify the *command* like this.

```php
phpbu\App\Backup\Cli\Binary::addCommandLocation('mysqldump', 'C:\work\xampp\mysql\bin');
phpbu\App\Backup\Cli\Binary::addCommandLocation('tar', 'C:\git\bin');
```

This has the advantage that you can use the exact same config file for Windows and Linux.
If you specify the `pathToCommand` option the config is bound to that system.

**Comment by sebastianfeldmann** [comment]
If you have more ideas on how to make *phpbu* more *Windows friendly* feel free to reopen this issue or a new one ;)
