### ISSUE TITLE
Sync JSON Config

### ISSUE THREAD

**Issue by todiadiyatmo** [sebastianfeldmann/phpbu#40]
Hi ,
I try to configure sync (configuration posted below) . However, when i run `phpbu` the sync command is not executed, is there anything wrong with my config ?
```
{
  "verbose": true,
  "logging": [
    {
      "type": "json",
      "target": "/home/kasatka/backup/one/one.json.log"
    }
  ],
  "backups": [
    {   
      "source": {
        "type": "mysqldump",
        "options": {
          "databases": "wordpress",
          "user": "root",
          "password": ""
        }
      },
      "target": {
        "dirname": "/home/kasatka/backup/one",
        "filename": "mysql-%Y%m%d-%H%i.sql",
        "compress": "bzip2"
      },
      "sync":{
        "type": "dropbox",
        "options": {
          "token": "myCrazyLongApiTokenThatIGotFromDropbox",
          "path": "/some/dir"
        }
      },
      "cleanup": {
        "type": "Quantity",
        "options": {
          "amount": "3"
        }
      }
      

    }

  ]
}
```

**Comment by sebastianfeldmann** [comment]
Hi,

it should be an array of `syncs` because it is possible to configure multiple `syncs`
```
"syncs": [
        {
            "type":
            ...
        }
]
```

I'll add a clear example to the phpbu documentation.

**Comment by sebastianfeldmann** [comment]
Hi,
I just added a `syncs` configuration to the son example configuration in the [phpbu manual](http://phpbu.de/manual/current/en/configuration.html#configuration.json).

Thanks for reporting this.
Cheers Sebastian

Related commit to the phpbu documentation can be found [here](https://github.com/sebastianfeldmann/phpbu-documentation/commit/444e1cae45a41729ef30d989b15c59a1e3654cd4)

**Comment by todiadiyatmo** [comment]
Great ! thank you for explaining this
