### ISSUE TITLE
mysqldump option

### ISSUE THREAD

**Issue by todiadiyatmo** [sebastianfeldmann/phpbu#41]
Hi,
Is it possible to add mysqldump specific option , for example `--lock-tables=false` ? Do you interesting to add such feature ? If i want to fork it, what file i should look at ? 

Kind Regards

**Comment by sebastianfeldmann** [comment]
Hi,
good suggestion, I will add it tonight.
If you want to do it in a fort you have to look at 2 files.

1. The Mysqldump Source class src/Backup/Source/Maysldump.php
Here you have to enable the new option

2. The Mysqldump executable class
src/Cli/Executable/Mysqldump.php
This class actually creates the command that gets executed.

But I will add it anyway so... :)

Cheers Sebastian

**Comment by sebastianfeldmann** [comment]
Hi,
I checked the mysqldump docs.
It looks like `--lock-tables` doesn't take a value, so to make it not lock tables you just don't add the option.
If you run `mysqldump` without `--lock-tables` it shouldn't lock any tables.

I added the option `lockTables` to version 2.1.15 so you can lock tables during dumping.
You can have a look at the [documentation](http://phpbu.de/manual/current/en/source.html#source.mysqldump)

Cheers, Sebastian

**Comment by todiadiyatmo** [comment]
Hi @sebastianfeldmann 
Actually what i mean is the ability to put extra mysql command ( no specific for lock-table).

**Comment by sebastianfeldmann** [comment]
Hi,
yes you are right it is time consuming :) to add all the options available to the `mysqldump` command.
But there are options that are not available in the `mysqldump` command that make it hard to add "custom/extra" options if that's what you want to achieve.
There are cases where phphbu will create two separate mysqldump commands and the specified custom options maybe don't make sense on both of them. So you could run into some messy problems with this.
Then there is the security issue you would add with this if the custom/extra options aren't escaped properly.

Can you please give me an example of what you want to achieve with `extraCommand`?

I still think it is best to separately add the options you need.
Indeed more work but more "secure" and better testable.
