### ISSUE TITLE
Cleanup Issue

### ISSUE THREAD

**Issue by todiadiyatmo** [sebastianfeldmann/phpbu#43]
Hi,
I just check my backup, and for the sync options, seems the sync ( remote ) backup is not clean up. However the local backup is perfectly clean up. The phpbu email said the clean up process is okay.

Here is my config : 
```
        "cleanup": {
            "type": "Quantity",
            "options": {
                "amount": "3"
            }
        },
        "syncs": [{
            "type": "sftp",
            "options": {
                "host": "xxx",
                "user": "xxx",
                "password": "xxx",
                "path": "xxx"
            }
        }]

```

Kind Regards,
Todi

**Comment by sebastianfeldmann** [comment]
Hi,
`Cleanup` is intended to only work locally. This has mainly two reasons.
You can configure phpbu to cleanup **all** local backups. And you can have different file structures on your local system and your sync target system, this makes cleaning up remotes, let's say "challenging" :)

Currently the only `Sync` that supports remote "cleanup" is the `Rsync` one by using the `delete` option.

You can have a look at the documentation [here](http://phpbu.de/manual/current/en/sync.html#sync.rsync)

Maybe, to use the name `Sync` wasn't the best Idea, it's a bit confusing. Sorry, my bad.

**Comment by sebastianfeldmann** [comment]
I will check the documentation and add a hint, that cleanup is only working locally except `Rsync`
I added a [Ticket](https://github.com/sebastianfeldmann/phpbu-documentation/issues/1) for the documentation repository.

Hope this helps a little :)

Cheers, Sebastian

**Comment by todiadiyatmo** [comment]
great thanks ! i will try the rsync command ! :D

**Comment by sebastianfeldmann** [comment]
I just updated the [phpbu cleanup documentation](http://phpbu.de/manual/current/en/cleanup.html).

**Comment by necenzurat** [comment]
it would be nice to have an separate cleaner for the remote part.
