### ISSUE TITLE
Idea: Get db credentials from project config

### ISSUE THREAD

**Issue by barryvdh** [sebastianfeldmann/phpbu#44]
It isn't recommended to put database credentials the git repository, so perhaps we should keep them out of the backup config also? And also, a lot of projects already have defined them anyways somewhere.

An option would be to provide some default project parsers, to load the configuration from the actual project.

Laravel -> Load database.php config file, or from .env directly.
Magento -> Parse local.xml file
Drupal -> Parse sites config file

Etc

**Comment by sebastianfeldmann** [comment]
Great idea.
Let's think of a good way to configure and implement this.

maybe something like
```xml
<credentials>
  <provider name="laravel-config" type="Laravel">
    <option name="path" value="path/to/laravel/config"/>
  </provider>
</credentials>

<backup>
   ...
   <source name="mysql">
     <option name="credentials.provider" value="laravel-config" />
     <option name="credentials.toUse" valu="mysql" />
   </source>
  ...
</backup>
```

And the inside the `Mysql` Source class.
```php
if ($this->useCredentialProvide()) {
    $credentials = $this->getCredentials($options);
    $username = $credentials->username;
    $password = $credentials->password;
}
```

**Comment by sebastianfeldmann** [comment]
Had to bump the major version for this but I think it was worth it.

```
<adapters>
  <adapter name="environment" type="dotenv">
    <option name="file" value=".env" />
  </adapter>
</adapters>

<backup>
   ...
   <source type="mysql" name="CoreDBBackup">
     <option name="user" valu="adapter:environment:DB_USER" />
     <option name="password" value="adapter:environment:DB_PASSWORD" />
   </source>
  ...
</backup>
```

I'll release version 4.0 as soon as possible.

**Comment by sebastianfeldmann** [comment]
I decided to use adapters to manipulate the configuration values
before creating the actual configuration. So the application does
not have to know anything about configuration adapters.

But to actually create adapters while handling the configuration,
I had to change the configuration loader interface in a backwards
incompatible way. So I had to increase the major version.

**Comment by planetahuevo** [comment]
2 questions: 
- Does this mean that we need to update our phpbu.xml files if we upgrade the version?
- Can we use this variables inside the "folder value"?
I mean: 
<option name="path" value="/something/something/adapter:environment:VARIABLE/something"/>

How can make this work? 

Thanks
