### ISSUE TITLE
question: Dropbox sync from cron

### ISSUE THREAD

**Issue by r3sist** [sebastianfeldmann/phpbu#45]
Hi!
I'm trying to run my phpbu setup from crontab.

The command line runner `phpbu --configuration=/home/d.xml` works fine. 
Also the cronjob (CentOS 7) is working: `0 * * * * /usr/local/bin/phpbu --configuration=/home/d.xml`, except the syncing:

> Exception 'phpbu\App\Backup\Sync\Exception' with message 'Error executing HTTP request: '
> in phar:///usr/local/bin/phpbu/Backup/Sync/Dropbox.php:101
> 
> backup mysqldump: OK, but skipped or failed Crypts, Syncs or Cleanups!

What am I missing? Why crontab can't execute HTTP request, while I have a working setup of phpbu?

Thank you for your help!

(I'm sorry for the spam in the issue tracker, I couldn't find any other maillist/forum etc...)

**Comment by sebastianfeldmann** [comment]
Issue tracker is fine 
I'm currently on the road and can't ivestigate this in detail. I will have a closer look at it this evening.
But here are some points to look at.

Which user is executing the cron?
The same one you are using?

What kind of shell is the cron user using, bash or any other one?

If you can execute phpbu including the Dropbox Sync my first guess would be user / permissions / environment problems.

Keep me posted
I will try to reproduce the issue later today.

**Comment by r3sist** [comment]
Helo Sebastian,
Thanks for the quick responde.

It's a VPS, with one root user. Cron shell is bash - as far as i can tell, I'm an absolute newbie. I've set up my enviroment (eg. cronjobs) through a web control panel (VestaCP).

**Comment by sebastianfeldmann** [comment]
Hi,

to make sure the expected user is executing the cron is:

* Login via ssh
* Run `crontab -l` to list all your crons

If the phpbu cron is **not** listed there proceed as follows:

* If you don't connect as root get root by using `su` (enter root password)
* Run `for user in $(cut -f1 -d: /etc/passwd); do echo $user; crontab -u $user -l; done`

This will list all user`s cron in a format like

    UserA
    * * * * /some/cron
    UserB
    UserB has no cron

This is just to make sure the expected user is executing the cron.

**Comment by r3sist** [comment]
Hi,
You were right, the web control panel creates different users. So, I used the classic `crontab -e` method, and added cronjob to the root user, and phpbu sync works now.

Thank you again. I should learn about these things...
And phpbu is awsome!

**Comment by sebastianfeldmann** [comment]
Hi,
that's good news. Always happy to help ;)
Thanks for the compliment
