### ISSUE TITLE
Support google cloud drive for sync

### ISSUE THREAD

**Issue by F21** [sebastianfeldmann/phpbu#49]
Since copy.com is now discontinued, I think google cloud drive is a good viable alternative (same amount of storage is offered in the free plan).

**Comment by sebastianfeldmann** [comment]
Hi,
sounds good

Cheers Sebastian

**Comment by sebastianfeldmann** [comment]
Some docs that might help.
https://developers.google.com/drive/v3/web/quickstart/php
https://developers.google.com/api-client-library/php/guide/media_upload
https://developers.google.com/api-client-library/php/auth/api-keys

**Comment by sebastianfeldmann** [comment]
This google API and documentation is driving me crazy!
This will not be done in version 5.0.0

**Comment by stainleebakhla** [comment]
Hi Sebastian,

Would really love it if you could also integrate Google Drive into this.

Thanks
Stainlee

**Comment by sebastianfeldmann** [comment]
I would love to as well
Have to confess I did not search like my life depends on it, but every other cloud storage was done in 30 to 60 min tops, so I gave up on google drive a while ago.
This doesn’t mean I will never integrate it, as soon as somebody points me to a working php script that uploads a file to google drive without oauth just simple key authentication I will try my best to reproduce it and then integrate it into phpbu.
But last time I checked the google documentation was just false and examples where only available for the old api version.... like I said ... very frustrating.

Like I said. If someone would do the google drive code, I would like netteste this into phpbu in no time ;)

**Comment by sebastianfeldmann** [comment]
After checking back the Xth time I finally managed to get the Google Drive example to work.
Documentation and Example code are still faulty, but at least in reasonable time fixable faulty.

I just finished the integration and this feature will be released with version 5.1

**Comment by stainleebakhla** [comment]
Thanks a lot Sebastian. Really appreciate the effort.
