### ISSUE TITLE
Amazon S3 error

### ISSUE THREAD

**Issue by necenzurat** [sebastianfeldmann/phpbu#50]
After painfully configuring the correct values for S3 demo below, maybe will make a pull request for the docs
```
      "syncs": [
        {
			"type": "amazons3",
			"options": {
			"key": "KEY",
			"secret": "SECRET",
			"bucket": "https://s3.amazonaws.com/bucket-name",
			"region": "us-east-1",
			"path": "/back"
		  }
        }
      ],
```

I get this exception and it's annoying.

````
Exception 'phpbu\App\Backup\Sync\Exception' with message 'The request signature we calculated does not match the signature you provided. Check your key and signing method.'
in phar:///app2/phpbu.phar/Backup/Sync/AmazonS3.php:130
````

Using the latest phpbu 2.1.15

And no, the keys and secret are correct, checked for whitespaces, and all of the above.

Any ideas ?

**Comment by sebastianfeldmann** [comment]
Hi,
here is an example xml config.
Try to remove the scheme and host for the bucket name.
```
<sync type="amazons3">
          <option name="key" value="KEY" />
          <option name="secret" value="SECRET" />
          <option name="bucket" value="phpbu" />
          <option name="region" value="eu-central-1" />
          <option name="path" value="/phpbu-backup/%Y" />
      </sync>
```
What version of PHP are you using?

**Comment by necenzurat** [comment]
Above 5.5 and using json.

And no, it threw other errors before that. Will try the xml version. But
nevertheless.

On Thursday, February 4, 2016, Sebastian Feldmann <notifications@github.com>
wrote:

> Hi,
> here is an example xml config.
> Try to remove the scheme and host for the bucket name.
>
> <sync type="amazons3">
>           <option name="key" value="KEY" />
>           <option name="secret" value="SECRET" />
>           <option name="bucket" value="phpbu" />
>           <option name="region" value="eu-central-1" />
>           <option name="path" value="/phpbu-backup/%Y" />
>       </sync>
>
> What version of PHP are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianfeldmann/phpbu/issues/50#issuecomment-180059500>
> .
>


-- 

--
*Costin Moise* aka necenzurat

Tel: *+4 0726.459.188* | Github <https://github.com/necenzurat> | Linkedin
<http://www.linkedin.com/in/necenzurat>

**Comment by sebastianfeldmann** [comment]
You can use json that shouldn't matter at all.
Have you tried to remove the scheme and host for your bucket value?

**Comment by necenzurat** [comment]
Yea, it said it must have s3.amazon.

On Thursday, February 4, 2016, Sebastian Feldmann <notifications@github.com>
wrote:

> You can use json that shouldn't matter at all.
> Have you tried to remove the scheme and host for your bucket value?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianfeldmann/phpbu/issues/50#issuecomment-180063143>
> .
>


-- 

--
*Costin Moise* aka necenzurat

Tel: *+4 0726.459.188* | Github <https://github.com/necenzurat> | Linkedin
<http://www.linkedin.com/in/necenzurat>

**Comment by sebastianfeldmann** [comment]
Hi, this configuration is working fine for me.
´´´
"syncs": [
        {
          "type": "amazons3",
          "options": {
            "key": "MYKEY",
            "secret": "MYSECRET",
            "bucket": "phpbu",
            "region": "eu-central-1",
            "path": "/phpbu-backup/%Y"
          }
        }
      ],
´´´

**Comment by necenzurat** [comment]
nope, i'm getting this error 
```
Exception 'phpbu\App\Backup\Sync\Exception' with message 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "s3.amazonaws.com".'
in phar:///usr/local/bin/phpbu/Backup/Sync/AmazonS3.php:130

```

**Comment by sebastianfeldmann** [comment]
I found this on the web:
http://www.sitefinity.com/developer-network/forums/set-up-installation/amazon-s3---must-be-addressed-using-the-specified-endpoint
This isn't really up to date, but maybe it helps.

If the bucket issn't the problem I would encourage you to install phpbu via composer and install the latest version of the AWS SDK (2.8.*) via composer.

You can check the AWS version bundled within the PHAR with `phpbu --manifest`

If this works with your composer installed phpbu it's a problem with the bundled AWS version and I will release an update with the latest 2.* version.

**Comment by necenzurat** [comment]
So, installed from composer
```json
{
    "require": {
        "phpbu/phpbu": "^2.1",
        "aws/aws-sdk-php": "2.8.*"
    }
}
````
And then i get this gem

```
Exception 'phpbu\App\Backup\Sync\Exception' with message 'The difference between the request time and the current time is too large.'
in /app2/vendor/phpbu/phpbu/src/Backup/Sync/AmazonS3.php:130
```

**Comment by sebastianfeldmann** [comment]
Please check your local system time.
Amazon is blocking requests with a time difference greater than 15 minutes.

**Comment by necenzurat** [comment]
fixed that, but no help

**Comment by sebastianfeldmann** [comment]
Still the time difference exception or back to "The request signature we calculated does not match the signature you provided. Check your key and signing method." ?

**Comment by necenzurat** [comment]
back to The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by sebastianfeldmann** [comment]
This is somehow the code phpbu executes to upload your backup to AWS S3.
```
use Aws\S3\S3Client;

require 'vendor/autoload.php';

$key = '';
$secret = '';
$localFile = ''; // test.txt
$region = ''; // aws region
$bucket = ''; // bucket name
$remoteFile = ''; // /foo/bar/test.txt

$s3 = S3Client::factory(
    [
        'signature' => 'v4',
        'region' => $region,
        'credentials' => [
            'key' => $key,
            'secret' => $secret,
        ]
    ]
);
$fh = fopen($localFile, 'r');
$s3->upload($bucket, $remoteFile, $fh, 'private');
```

This is nearly copy & paste of the AWS documentation.
With the code above you can test the AWS functionality without phpbu in your way.

This way you hopefully find your problem.

**Comment by necenzurat** [comment]
The upper code says the same error. :cry:  

Ok, so i did a test with [s3tools](http://s3tools.org/s3cmd) and it worked.

**Comment by sebastianfeldmann** [comment]
This sounds more and more like a php environment problem.
Do you have the opportunity to test it on a different system?
Preferably one with a differently setup os and php version.

**Comment by necenzurat** [comment]
tested it on another server, same problem, maybe it's the sdk?
error 
```

PHP Fatal error:  Uncaught Aws\S3\Exception\SignatureDoesNotMatchException: AWS Error Code: SignatureDoesNotMatch, Status Code: 403, AWS Request ID: 912A1E9FAC564353, AWS Error Type: client, AWS Error Message: The request signature we calculated does not match the signature you provided. Check your key and signing method., User-Agent: aws-sdk-php2/2.8.27 Guzzle/3.9.3 curl/7.38.0 PHP/5.6.9-0+deb8u1
  thrown in /home/test-aws/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php on line 91
```

**Comment by sebastianfeldmann** [comment]
I find that hard to believe. The AWS sdk is a widely used framework and uploading a file is so basic that it's very unlikely that there is a bug that exists in version 2.7.x and still exists in 2.8.x
But nothin is impossible.
Don't know how I can help you from here :(

**Comment by sebastianfeldmann** [comment]
I just release version 3.0.0 with the latest AWS SDK version.
Hopefull this fixes your problem.

Just execute
`$ phpbu --self-update`
to upgrade to the latest version

**Comment by sebastianfeldmann** [comment]
Hi @necenzurat, I will close this ticket for now, if you have any further remarks feel free to reopen it.

**Comment by necenzurat** [comment]
3.0.0 
it's quite an improvement, now i get this gem of an error:

`PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in phar:///usr/local/bin/phpbu/Backup/Sync/AmazonS3v3.php on line 49`
 
:cry:

**Comment by sebastianfeldmann** [comment]
OK looks like the Amazon stream wrapper can't open a stream to the S3 bucket.
And I missed to validate that the stream was created successfuly. So you get a warning instead of an exception and phpbu thinks everything went fine.

It drives me crazy that this isn't working in your environment

I still have to fix the missing validation thingy

**Comment by necenzurat** [comment]
so yea, it was my fault. the correct settings for the v.3.0.1 and amazon with json sync are:

````json
 "syncs": [
        {
			"type": "amazons3",
			"options": {
			"key": "___KEY___",
			"secret": "___SECRET___",
			"bucket": "bucket-name",
			"region": "us-east-1", 
			"path": "back/%Y" 
		  }
        }
````
Region: us-east-1 ([region list](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region))

**Comment by sebastianfeldmann** [comment]
:smile: happy it works

**Comment by necenzurat** [comment]
me too and thanks for this awesome tool
