### ISSUE TITLE
Tar source archive `removeDir` is not being used

### ISSUE THREAD

**Issue by sebastiaanluca** [sebastianfeldmann/phpbu#51]
`\phpbu\App\Backup\Source\Tar` has a `removeDir` setting in its `setup` method to specify if the source directory should be removed after archiving, but it is not being used anywhere.

Shouldn't this be passed to the executable's (`\phpbu\App\Cli\Executable\Tar`) `removeSourceDirectory` method? See https://github.com/sebastianfeldmann/phpbu/blob/master/src/Backup/Source/Tar.php#L131.

**Comment by sebastianfeldmann** [comment]
Hi,
right now this is a undocumented feature idea ;)
I was a bit to anxious to add a `rm -rf`command to delete the directory.

The next major version of phpbu (3.0) will feature a `--simulate` option to run phpbu without executing anything but seeing all phpbu would do to make sure everything works as intended.

Maybe then I find the courage to implement this feature ;)

**Comment by sebastiaanluca** [comment]
Good thinking, can't be to careful when running `rm -rf` on anything! I'll let the system garbage collect the remaining files in `/tmp` then, no problem.

**Comment by sebastianfeldmann** [comment]
I activated the `removeSourceDir` option.
Will be released in 3.1.1

**Comment by sebastianfeldmann** [comment]
I will try to update the Laravel integration to version ~3.1 in the next couple of days so you can benefit from this changes.

**Comment by sebastiaanluca** [comment]
Sweet man, thanks! No rush on the Laravel integration. I'm using your package directly using the `Runner` and `Configuration` classes :)
