### ISSUE TITLE
Use rsync as source to collect files from remote servers

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianfeldmann/phpbu#52]
Create `rsync` source.

The idea it to collect files (backups) from a remote server.
This is great if the production server can't access the backup server in a local network.
So instead of pushing backups to the backup server use phpbu to pull all created backups.

**Comment by sebastiaanluca** [comment]
:) Just put my current code online @ https://github.com/sebastiaanluca/server-backup-app. Currently using Laravel to run commands (one per project) that are to be scheduled using CRON. I just want to get it all working first, so don't mind the horrible writing style. I subclassed the sync rsync class to act as a source, but ideally you'd want to create a new class from scratch for that.

**Comment by sebastianfeldmann** [comment]
In this case I don't mind the code at all, the idea is just awesome.
Simple to implement and a big improvement.
Wish I'd came up with it ;)

**Comment by sebastianfeldmann** [comment]
@sebastiaanluca I just released version 3.2.0 with a rsync source.
I did some rsync refactoring that might break your subclassing model.
Just to be sure have a look at it before upgrading to version 3.2.0
