### ISSUE TITLE
Invalid PHP version requirement

### ISSUE THREAD

**Issue by hdogan** [sebastianfeldmann/phpbu#62]
phpbu version 3 requires minimum 5.4 (see version 3.0 changelog) but aws-sdk v3 requires minimum 5.5. So phpbu is unable to run on php 5.4.

Tested phpbu.phar (3.1.3) archive on PHP 5.4.45
Result is:

```PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in phar:///root/phpbu.phar/lib/aws-sdk/functions.php on line 36```

**Comment by sebastianfeldmann** [comment]
*ups*
Do you use the AWS sync or does this even happen if you execute phpbu without syncing to AWS?

**Comment by hdogan** [comment]
It happens event if you don't give any configuration or command line option.
It was  `phpbu.phar --version` output. So it happens without running any job.

**Comment by sebastianfeldmann** [comment]
That's not good :(
So if you need phpbu to run with 5.4, for now you have to install it via composer, and use AWS v2.
And I have to decide if I return to AWS version 2 or update the requirements to version 5.5

**Comment by hdogan** [comment]
I think >= 5.5 is reasonable requirement, since 5.4 is already end of life and 5.5 support will be ended soon (http://php.net/supported-versions.php) . The problem is just phpbu web-site (or changelog) should mention that. I've switched to version 2 of phpbu and it's working and doing it's job well atm.

**Comment by sebastianfeldmann** [comment]
I think you are right. I will update the requirement documentation.
Thanks for reporting this.

**Comment by sebastianfeldmann** [comment]
I updated the `README.md` and the documentation http://phpbu.de/manual/current/en/installation.html#installation.requirements that if you want to use the PHAR the required version is PHP 5.5

Thanks for reporting
