### ISSUE TITLE
mysqludmp failed; can't create/write to file

### ISSUE THREAD

**Issue by ZaphodBBX** [sebastianfeldmann/phpbu#64]
Hi,

When trying an phpbu backup I get a mysql dump error:
Exception 'phpbu\App\Exception' with message 'mysqldump failed:mysqldump: Got error: 1: Can't create/write to file '/tmp/mysql/mysqldump-20160523-0830.sql.dump/Afwezigheden.txt' (Errcode: 13) when executing 'SELECT INTO OUTFILE'

I know this is most likely a permissions error, but I can't get it to work, I have even tried setting chmod 777 -R on the target dir, I have changed the owner/group to mysql user, I have executed phpbu command as mysql user,...

Weird thing is the tool does create an Afwezigheden.sql file. But refuses to create the Afwezigheden.txt file. (I'm using the filePerTable option).

So I'm kind of running out of idea's. Anyone have a possible solution to this problem?

**Comment by ZaphodBBX** [comment]
PS: when setting filePerTable to false, the backup is completed successfully.

**Comment by sebastianfeldmann** [comment]
Does you MySQL user have the permission `FILE`
```mysql
GRANT FILE ON *.* TO 'myUser'@'localhost';
```

**Comment by sebastianfeldmann** [comment]
When using the `filePerTable` option `mysqldump`is using the `INTO OUTFILE` functionality intenally.
So you mysql user has to be able to execute something like this.
```sql
SELECT id, name, email INTO OUTFILE '/tmp/result.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
ESCAPED BY ‘\\’
LINES TERMINATED BY '\n'
FROM users WHERE 1
```

**Comment by ZaphodBBX** [comment]
I have confirmed my user has correct write file rights. (even tried with mysql root user).
I can execute the query you provide successfully...

**Comment by ZaphodBBX** [comment]
Okay so: 
Can't create/write to file '/tmp/latest.dump/Afwezigheden.txt' (Errcode: 13) fails,
but when I execute the query to '/tmp/Afwezigheden.txt' it works. The latest.dump folder is created by the php script I guess? How do I make sure mysql has write rights to the folder created by the php script. (i have already tried executing the phpbu command as mysql user)

**Comment by sebastianfeldmann** [comment]
Yes you are right php is creating the directory, it even tries to make sure it is writable for everybody.
```
$old = umask(0);
mkdir($this->getDumpTarget($target), 0777, true);
umask($old);
```

**Comment by ZaphodBBX** [comment]
Yes, I noticed the directory properties rights are: drwxrwxrwx. 
Do you know something else I can try?

**Comment by sebastianfeldmann** [comment]
For me, this config
```xml
<backup>
    <source type="mysqldump">
        <option name="user" value="root" />
        <option name="databases" value="dbname" />
        <option name="filePerTable" value="true" />
    </source>
    <target dirname="backup/mysql" filename="mysql-%Y%m%d-%H%i.sql" compress="bzip2" />
</backup>
```
results in this
```
phpbu 3.1-dev

Runtime:       PHP 7.0.2-1~dotdeb+8.1
Configuration: /var/phpbu/phpbu.xml

Time: 1.87 seconds, Memory: 2.00Mb

OK (1 backup, 0 checks, 0 crypt, 0 syncs, 0 cleanups)
```

When I run `phpbu --simulate` I get something like this
```
phpbu 3.1-dev

Runtime:       PHP 7.0.2-1~dotdeb+8.1
Configuration: /var/phpbu/phpbu.xml

backup: [mysqldump] *******************************************************
backup data:
/usr/bin/mysqldump --user='root' 'dbame' --tab='/var/phpbu/backup/mysql/dump-20160523-1100.sql.dump'
(/bin/tar -jcf '/var/phpbu/backup/mysql/dump-20160523-1100.sql.bz2' -C '/var/phpbu/backup/mysql' 'dump-20160523-1100.sql.dump' && rm -rf '/var/phpbu/backup/mysql/dump-20160523-1100.sql.dump')
ok
```
the important part is
```
mysqldump --user='root' 'dbame' --tab='/var/phpbu/testdump'
```
Can you create a directory `/var/phpbu/testdump` manually and execute the query above to see if it works without phpbu

**Comment by ZaphodBBX** [comment]
This fails:
`/usr/bin/mysqldump --user='jos' --password='******' --host='localhost' 'VAH_DEMO' --tab='/tmp/backups.dump' `

This works:
`/usr/bin/mysqldump --user='jos' --password='******' --host='localhost' 'VAH_DEMO' --tab='/tmp'`

Manually creating a folder and trying to dump there also fails :s :s

**Comment by sebastianfeldmann** [comment]
Maybe some special `tmp` umask voodoo.
Have you tried to not use `/tmp`

**Comment by sebastianfeldmann** [comment]
Manually creating the target folder with `drwxrwxrwx` still fails?

**Comment by ZaphodBBX** [comment]
yeah this is freaking me out, I've tried everything, chmod 777 -R, chown mysql:mysql, create the folder using mysql  user, it's like mysqldump refuses to dump to any other folder then /tmp

**Comment by sebastianfeldmann** [comment]
I found this
http://stackoverflow.com/questions/2783313/how-can-i-get-around-mysql-errcode-13-with-select-into-outfile
If you use ubuntu have a look there and tell me if it helps ;)

**Comment by ZaphodBBX** [comment]
it's currently running on a CentOS system

**Comment by sebastianfeldmann** [comment]
Your are welcome ;)
Sorry I couldn't be of much help.

Last thing:
The stackoverflow post mentioned `AppArmor` as the one stoping `mysql` from writing to different directories.
So if you are using `AppArmor` or something similar check the config files for it.

**Comment by duanegran** [comment]
I wish I had more to share on this issue.  I'm the one who proposed the filePerTable feature and I use CentOS and also get this error.  I've been trying periodically to figure it out with no luck.  If I make a break through I'll post back here again though.

**Comment by sebastianfeldmann** [comment]
That would be great, hope you find the problem soon ;)

**Comment by volodymyr-kushnir** [comment]
For those who still have this problems please check your [**secure_file_priv**](https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_secure-file-priv) variable. On CentOS 7.3-1611 and MySQL 8.0.1 it's set to `/var/lib/mysql-files/`. Set it to empty string to remove this security check.

**Comment by sebastianfeldmann** [comment]
Thanks, I will include this as a note in the `phpbu` docs
