### ISSUE TITLE
Sia decentralized backups

### ISSUE THREAD

**Issue by kunkinkan** [sebastianfeldmann/phpbu#68]
See http://sia.tech - Basically you can rent disk space on other user's computers. With 6-times redundancy.

API docs are here: https://github.com/NebulousLabs/Sia/tree/master/doc

**Comment by sebastianfeldmann** [comment]
Do you know of any easy to use PHP client lib to interact with the sia api.
Because building a solid client can be quite some work ;)

**Comment by kunkinkan** [comment]
I only know of this one: https://github.com/pmknutsen/PHP-Sia but it seems to not be updated in quite some time so no idea if that is outdated or not..

**Comment by sebastianfeldmann** [comment]
Currently there is no viable SIA php client out there to handle file uploads, at least to my knowledge

So I will not add this to the phpbu core.
But I would love to see a sync plugin ;)
