### ISSUE TITLE
Missing docs for extending phpbu

### ISSUE THREAD

**Issue by F21** [sebastianfeldmann/phpbu#7]
The docs on extending phpbu seems to be missing some sections: http://phpbu.de/documentation.html#extend-source

**Comment by sebastianfeldmann** [comment]
You are right. I'm trying to release version 2.0.0 this week. For version 2.x I have have to make some documentation updates and if everything is going as planned, this will include the *extending phpbu* section.

**Comment by sebastianfeldmann** [comment]
I just updated the documentation. The "extending phpbu" section is still work in progress.
If you have any further questions don't hesitate to ask them here.
