### ISSUE TITLE
S3 Backup "Empty reply from server"

### ISSUE THREAD

**Issue by danimbrogno** [sebastianfeldmann/phpbu#72]
Hi, Occasionally I receive this error on my backups:

```
Exception 'phpbu\App\Backup\Sync\Exception' with message 'An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 1215: Error executing "UploadPart" on "..."; 
AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) ' in /home/backup/vendor/phpbu/phpbu/src/Backup/Sync/AmazonS3v3.php:49
```

Is this simply a connectivity issue? My backup is about 10 gigabytes in size, so it is possible that there is a blip in the network. Any suggestion for how to improve the likelihood of the backup completing?

**Comment by sebastianfeldmann** [comment]
Hi,
you are right that sounds like a connection problem.
The only thing that comes to mind is to split the backup into smaller parts, and do a retry if a small part fails, but that has to be implemented first.

It it's a directory backup maybe this works.
You can split your single directory backup into multiple directory backups
so change
backup /uploads
to
backup /uploads/foo
backup /uploads/bar
backup /uploads/baz

**Comment by danimbrogno** [comment]
Thanks, for the advice. The backup is a WordPress website, and the vast majority of files being backed up are in monthly subfolders in the uploads directory, so splitting it up isn't so practical (i.e I'd have to update the config to add new months as time goes by).

I was considering writing a custom sync'er that would split the tar file into 1gb parts and upload them individually, however, I realized that my server is out in California and I was using the US East 1 region for my backup disk. I switch to a backup disk in US West 1 and it  completed with no trouble.

**Comment by sebastianfeldmann** [comment]
Happy it works.
None the less, I will have a look at a splitting option for the sync :)

Cheers, Sebastian
