### ISSUE TITLE
RuntimeException with message ''mysqldump' was nowhere to be found please specify the correct path' in C:/xampp/htdocs/seraphim/vendor/phpbu\src\Util\Cli.php:109

### ISSUE THREAD

**Issue by howellkit3** [sebastianfeldmann/phpbu#76]
This is for Laravel-phpbu. (https://github.com/sebastianfeldmann/phpbu-laravel/issues/3)

![phpbu](https://cloud.githubusercontent.com/assets/20956246/21558254/e043f338-ce71-11e6-848a-21048f5c45e7.png)
![phpbu-xml](https://cloud.githubusercontent.com/assets/20956246/21558255/e0473a16-ce71-11e6-9fee-4bb3e63344ec.png)

Giving my code, Im still unable to backup successfully.

This is my error
![phpbu-error](https://cloud.githubusercontent.com/assets/20956246/21558266/124a08a4-ce72-11e6-9871-57ca1e4d31e0.png)

How can I specify the correct path?

**Comment by sebastianfeldmann** [comment]
Hi, there is an option for the mysql source called `pathToMysqldump`
```xml
<option name="pathToMysqldump" value="/path/to/your/mysqldump/bin">
```
Sadly the documentation in incomplete in this case, I will update the documentation ASAP.

Hope this helps.
Cheers, Sebastian

**Comment by sebastianfeldmann** [comment]
If you are using Laravel you should be able to define it like this
```php
  'source' =>[
    'connection' => 'mysql',
    'option' => [
      'pathToMysqldump' => '/path/to/your/mysqldump/bin',
      ...
    ]
```

**Comment by sebastianfeldmann** [comment]
Let me know if this works

**Comment by sebastianfeldmann** [comment]
I updated the documentation and added the missing option to all available source types.

https://phpbu.de/manual/current/en/source.html#source.mysqldump

**Comment by howellkit3** [comment]
Thanks for the response. I think  mysqldump has been specified but I got this error.
![phpbu-code](https://cloud.githubusercontent.com/assets/20956246/21567596/48f3282e-cee8-11e6-83df-dd0c0d97fd40.png)
![phpbzip2](https://cloud.githubusercontent.com/assets/20956246/21567597/48f44a38-cee8-11e6-95de-ca90dadb5a3b.png)

**Comment by howellkit3** [comment]
Is there a section in the documentation about compression. Im looking for it but unfortunately I was not able to find it.

**Comment by sebastianfeldmann** [comment]
You defined `bzip` as your target compression.
```xml
<target ... compress="bzip">
```
phpbu assumes, that you have the bzip2 executable installed and that it is in your PATH.
You can try `zip` but it will only work if the zip executable is in your PATH.
Sadly you can't define a custom path to the compression binaries at the moment.

You are absolutely right, the documentation is lacking in terms of compression.
I will update the docs with some information about compression soon.

**Comment by sebastianfeldmann** [comment]
If everything fails try to remove the `compress="*"` from your config to check if it will work without any compression

**Comment by howellkit3** [comment]
Hi,

I was able to back up the database but I still receiving a Failure message.
![phpbu output](https://cloud.githubusercontent.com/assets/20956246/21568278/2efabe04-ceee-11e6-8bd8-f11e2ef8c8c8.png)
![phpbu-failure](https://cloud.githubusercontent.com/assets/20956246/21568279/2faa5e9a-ceee-11e6-82fe-3b7cdcb4a12d.png)

**Comment by sebastianfeldmann** [comment]
You configured a check.
`MinSize 10MB`
And you Backup is only 5KB in size ;)

**Comment by howellkit3** [comment]
Cool !

What Ill do next is to automate it everyday. Do you have something that will help to call this function on controller to schedule it in scheduler?

Thanks!

**Comment by sebastianfeldmann** [comment]
Sorry not really, scheduling is currently not a focus of phpbu.
Sadly im not that familiar with Windows, so I don't know how to schedule tasks in Windows.
On Linux or macOS I could give you some hints, for Linux there even is some info inside the documentation.
