### ISSUE TITLE
Support for JSON and YAML config

### ISSUE THREAD

**Issue by F21** [sebastianfeldmann/phpbu#8]
It would be awesome if the configuration files could be written in JSON and YAML, which are easier to read than XML.

**Comment by sebastianfeldmann** [comment]
Version 2.0.0 actualy contains the foundation to do just that. I seperated the configuration logic and the file parsing logic. In version 2.0.1 I plan to include a json config parser. For now, adding YAML support is very unlikely, but who knows, never say never ;)

**Comment by sebastianfeldmann** [comment]
I just added support for `json` configuration files.

`phpbu --configuration=phpbu.json`
