### ISSUE TITLE
add "Exclude" option for tar backup 

### ISSUE THREAD

**Issue by tkapluk** [sebastianfeldmann/phpbu#83]
Please, add exclude option for backup directories ( tar). 

We have folders that don't need to backup: cache, sessions, etc.
Also I have error in tar backups:

> Exception 'phpbu\App\Exception' with message 'tar failed: /usr/bin/tar: source/var/session: file changed as we read it ' in phar:///usr/local/bin/phpbu/Backup/Source/Tar.php:112

phpbu 4.0.3

**Comment by sebastianfeldmann** [comment]
Hi,
you can commit the read errors by adding the `ignoreFailedRead` option.

```xml
<option name="ignoreFailedRead" value="true"/>
```

**Comment by sebastianfeldmann** [comment]
adding the --exclude option is in progress

**Comment by sebastianfeldmann** [comment]
I just released phpbu 4.0.4 with the new tar `--exclude` option

For example if you want to exclude `foo/bar` and `fiz/baz` from your tar use something like this.

```xml
<option name="exclude" value="foo/bar,fiz/baz"
```

**Comment by tkapluk** [comment]
Thanks! Works fine.

**Comment by planetahuevo** [comment]
@sebastianfeldmann Can we add 2 options for exclude? 
I have two list of exclusions to add to the tar. I wonder if that will work (it does on tar).

Thanks!
