### ISSUE TITLE
Uncaught Error: Class 'JmesPath\Env' not found in phar

### ISSUE THREAD

**Issue by YadrovSergey** [sebastianfeldmann/phpbu#85]
PHP Fatal error:  Uncaught Error: Class 'JmesPath\Env' not found in phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/aws-sdk/Result.php:30
Stack trace:
#0 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/aws-sdk/S3/PermanentRedirectMiddleware.php(51): Aws\Result->search('"@metadata".eff...')
#1 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/guzzlehttp/promises/Promise.php(203): Aws\S3\PermanentRedirectMiddleware->Aws\S3\{closure}(Object(Aws\Result))
#2 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/guzzlehttp/promises/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(Aws\Result), Array)
#3 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/guzzlehttp/promises/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/guzzlehttp/guzzle/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#5 phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/guzzleh in phar:///home/projects/tvoydnevnikapp/v2.0.16/phpbu.phar/lib/aws-sdk/Result.php on line 30

**Comment by sebastianfeldmann** [comment]
I just released phpbu 4.0.5 hopefully you issue is fixed there ;)

**Comment by sebastianfeldmann** [comment]
Thanks for reporting
