### ISSUE TITLE
Use multithread compressor

### ISSUE THREAD

**Issue by mudragel** [sebastianfeldmann/phpbu#87]
How I can use lbzip2 as directory compressor? 
Like this:
tar cf linux2.tar.bz2 linux --use-compress-program=lbzip2

**Comment by sebastianfeldmann** [comment]
```xml
<backup>
  <source type="tar">
    <option name="path" value="/some/dir"/>
  </source>
  <target dirname="/backup" filename="dir-%Y%m%d-%H%i.tar" compress="bzip2"/>
<backup>
```

This will create a `/backup/dir-20170308-2005.tar.bz2` containing `/some/dir`

Hope that helps

**Comment by mudragel** [comment]
I mean lbzip2 not standard bzip2. lbzip2 can use multithread for compressing as mentioned at http://www.cnx-software.com/2016/12/16/compress-decompress-files-faster-with-lbzip2-multi-threaded-version-of-bzip2/

**Comment by sebastianfeldmann** [comment]
Currently there is now way to do so :/

**Comment by mudragel** [comment]
It will be a cool feature!

**Comment by sebastianfeldmann** [comment]
Definitely ;)

**Comment by sebastianfeldmann** [comment]
I just backported the new feature to phpbu 4.0.8
You can use it with a configuration like this.
```xml
<phpbu>
<backups>
  <backup name="foo">
    <source type="tar">
      <option name="path" value="/dir/to/compress"/>
      <option name="compressProgram" value="lbzip2"/>
    </source>
    <target dirname="backup/src" filename="backup-%Y%m%d-%H%i.tar" compress="zip"/>
  </backup>
</backups>
</phpbu>
```

This should result in a tar command like this
```bash
tar --use-compress-program='lbzip2' -cf backup/src/backup20170329-1500.tar.bz2 -C '/dir/to' 'compress'
```

Hope that helps

Cheers Sebastian
