### ISSUE TITLE
Support for cloud storage using OpenStack/Swift

### ISSUE THREAD

**Issue by KnightAR** [sebastianfeldmann/phpbu#88]
I'm using OVH for cloud storage, and they use OpenStack, Can we add support for OpenStack?

**Comment by sebastianfeldmann** [comment]
I found this php lib https://github.com/php-opencloud/openstack.
With this it should be possible quiet easily.

Sadly this lib if php7 only so it will not work in phpbu 4.x but only in the upcoming version 5.x

**Comment by KnightAR** [comment]
I have upgraded to PHP7 and phpbu 5.x, any news on when this feature would be implemented?

**Comment by sebastianfeldmann** [comment]
No actual plans yet #sorry
But thanks for reminding me, after v5 is php7 only this should be easy to implement.

Any suggestions where I can setup some test storage with an openstack api?

Preferably for free, just to test if everything works. ;)

**Comment by KnightAR** [comment]
https://www.cloudvps.com/openstack/object-store

They offer a two week free trial of openstack storage I've never used it
before but it may belp
