### ISSUE TITLE
TLS issue when sending via SMTP

### ISSUE THREAD

**Issue by TheCelavi** [sebastianfeldmann/phpbu#89]
I got this error message:

    Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first

When sending via SMTP.

Configuration:

        <log type="mail">
            <option name="sendOnlyOnError" value="true"/>
            <option name="recipients" value="xxx@xxx.com"/>
            <option name="transport" value="smtp"/>
            <option name="sender.mail" value="xxx@xxx.com"/>
            <option name="sender.name" value="XXX"/>
            <option name="smtp.host" value="xxx@xxx.com"/>
            <option name="smtp.username" value="xxx@xxx.com" />
            <option name="smtp.password" value="xxx" />
            <option name="smtp.port" value="587" />
            <option name="smpt.encryption" value="tls" />
        </log>

Tested configuration via Swift mailer programmatically, it works. What is wrong here?

**Comment by sebastianfeldmann** [comment]
Good question.
Please have a look at line 296 - 318 in the phpbu mail logger  https://github.com/sebastianfeldmann/phpbu/blob/master/src/Log/Mail.php#L296-L318
Maybe my setup is different from your "programmatic" approach.

**Comment by sebastianfeldmann** [comment]
Can you post your "programmatic" configuration. Then I can check for differences

**Comment by TheCelavi** [comment]
Difference is here:

    Swift_SmtpTransport::newInstance('xxx.com', 587, 'tls')

But that should not be a problem, something strange is happening here... Let me investigate further more...

**Comment by TheCelavi** [comment]
OMFG!!! I am soooooo embarrassed! It was an f**** typo:

    <option name="smpt.encryption" value="tls" />

SMPT??!?!? What the hell!?!?!?!

Sorry dude, thank you so much on your time. I am an idiot. 

******************************

While we are here :) I am using IntelliJ/PHP storm for my development and for creating XML documents there is a awesome built in support for XML Schema. 

Provided XML Schema for this project could be little more specific, perhaps, in order to avoid this kind of errors... What do you think? If I find a time, maybe I can improve it a little bit and send you a PR...

**Comment by sebastianfeldmann** [comment]
Don't worry about it, happens to me all the time!
Thanks for taking the time to investigate.

Improving the XSD would be nice though and PR are always welcome ;)
