### ISSUE TITLE
Support for XZ file compression

### ISSUE THREAD

**Issue by KnightAR** [sebastianfeldmann/phpbu#93]
XZ allows database dumps to be compressed way better then gzip or bz2. Can support be added for XZ?

**Comment by sebastianfeldmann** [comment]
This is a great idea, if have a prototype working on my laptop. I'm currently out snowboarding. I will integrate it when I'm back at home with some proper internet connection ;)

**Comment by sebastianfeldmann** [comment]
I added support for `zx` compression, currently only available in `dev-master`.

You can use it with something like

```xml
<target ... compress="xz" />
```

For `tar` commands the `J` option is used for simple file compression  the `xz` binary is executed directly.

**Comment by sebastianfeldmann** [comment]
Will be released with version 5.0.0
