### ISSUE TITLE
--set-gtid-purged option is absent for mysqldump adapter.

### ISSUE THREAD

**Issue by oprokidnev** [sebastianfeldmann/phpbu#94]
Mysql dump fails when I try to make a dump against mysql master host.

**Comment by sebastianfeldmann** [comment]
Can you please paste the generated `mysqldump` command and a fixed one that works for you.

You can use `phpbu --simulate` to display the `mysqldump` command phpbu executes without actually executing it.

Thanks

**Comment by oprokidnev** [comment]
@sebastianfeldmann 
Sorry for my quickly conclusions.  It was just a warning. *mysqldump* failed due to other reasons.
Nevertheless, It would be cool to have this option in futher releases. 

```/usr/local/bin/mysqldump --user='root' --password='******' --host='mysql3' --single-transaction 'site' | /usr/bin/gzip > /home/site/data/backups/2017-05-02.sql.gz```
```
Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events
```

**Comment by sebastianfeldmann** [comment]
I just added the ` --set-gtid-purged` option to the version 5 release candidate.
Hope I can release it soon.
