### ISSUE TITLE
Integration with framework other than Laravel

### ISSUE THREAD

**Issue by Zaporozhec7** [sebastianfeldmann/phpbu#95]
Hello. Firstly i want thanks very much for this great tool. 
I want integrate it in my project that build on top of Phalcon framework and use MongoDb as database, but i did not find any documentation about custom integrations throught php source. 
**Is it possible to use Phpbu functions (Classes, etc.) directly  from php code, without using shell_exec() and similar functions to call Phpbu with console commands?**
 I have tried understand how this done in **sebastianfeldmann/phpbu-laravel**, but for now did not understand any. 
Is it possibly to use class **phpbu\App\Cmd** from PHP code?

**Comment by sebastianfeldmann** [comment]
Hi, great you find it useful ;)
OK calling from PHP
The `Cmd` class is only for CLI usage.
The Laravel integration is done by using the `Runner` and `Configuration` classes
https://github.com/sebastianfeldmann/phpbu/blob/master/src/Runner.php
https://github.com/sebastianfeldmann/phpbu/blob/master/src/Configuration.php
The `Configuration` basically represents an XML or Json configuration with all the options.
The `Runner` is executing all the commands.

So easiest way to integrate phpbu would creating a valid `Configuration` and pass it to the `Runner` to execute it.

But you can off course use Source, Check, Crypt, Sync and Cleanup classes directly, but for this you have to take a deep dive into the phpbu source.

I would recommend the same approach I used for the Laravel integration.

If you have any questions, don't hesitate to ask ;)

Cheers, Sebastian

**Comment by Zaporozhec7** [comment]
@sebastianfeldmann ,
Thank you for such fast response. I just was tried to run **phpbu\App\Cmd** directly with this code:

```
(new Cmd())->run([
    '--configuration=PATH-TO-MY-CONFIG',
]);
```
And it was made backup without any errors. 
Although if you as author of this tool said that right way is using it with helper classes, as this done in Laravel integration, i will try use this  way.
Thank you again for help.

**Comment by sebastianfeldmann** [comment]
If you use a standard phpbu configuration file this is definetly the way to go.
Creating the Configuration instance by hand is only necessary if you want to use your own project configuration format
