### ISSUE TITLE
Error with filePerTable

### ISSUE THREAD

**Issue by gavinbenda** [sebastianfeldmann/phpbu#96]
Came up with nothing via Google, just thought I'd check in here and see if there were any hints.
When trying to run a pretty simple, local backup with filePerTable=true, I get:
```
mysqldump: --databases or --all-databases can't be used with --tab
```

Here is my config file:
Running PHP7.1/mySQL v5.7.18 on Ubuntu

```
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/4.0/phpbu.xsd">
  <backups>
    <backup>
      <!-- backup source -->
      <source type="mysqldump">
        <option name="filePerTable" value="true"/>
        <option name="user" value="root"/>
        <option name="password" value="*******"/>
      </source>
      <!-- where should the backup be stored -->
      <target dirname="/path/to/backup"
              filename="mysqldump-%Y%m%d-%H%i.sql"
              compress="gzip"/>
      <!-- check the created backup -->
      <check type="SizeMin" value="100K"/>
      <!-- cleanup the backup location
           as soon as all created backups exceed 500MB
           remove oldest backups -->
      <cleanup type="Capacity">
        <option name="size" value="500MB"/>
      </cleanup>
    </backup>
  </backups>
</phpbu>
```

Works (writing to a single file) with that option turned off.

**Comment by sebastianfeldmann** [comment]
Hi,

if you do not specify a specific database to backup `phpbu` assumes that you want to dump `--all-databases`.
If you want to use the `--tab` option you have to specify the database you want to backup, otherwise you are experiencing the error you mentioned.
All you have to do is to add the `databases` config option.

```xml
  <!-- optional, default=all -->
  <option name="databases" value="my-db" />
```

But be aware, that backups created with `--tab` are completely different from "normal" MySQL dumps.
You have to restore them in a different way. For more details on this have a look at the documentation.
https://dev.mysql.com/doc/refman/5.7/en/reloading-delimited-text-dumps.html

Hope that helps.

Cheers, Sebastian

**Comment by gavinbenda** [comment]
That makes sense, thanks Sebastian. My hope was I would be able to backup every database, within its own .sql file (tables separated also is optional), rather than all merged into one single .sql file. We have about 100 databases which get added to from time to time so --all-databases is required.

**Comment by sebastianfeldmann** [comment]
Currently, there is no way to automatically create separated "normal" SQLdump files for each database.
But this is a nice idea.

A solution would be to generate the `phpbu.xml` configuration with a script.
And split the backup into 100 backups, but this is only a workaround.

**Comment by sebastianfeldmann** [comment]
To actually dump all databases to a separate file, with a separate `mysqldump` command, it would require `phpbu` to execute a `show databases;` mysql query to know about all the databases to dump.

I'm not sure if this is the right approach, so for now I'll close this issue.

IMHO
If you create new databases, the database should be used for a project or an app. And if so the database should appear in the `phpbu` configuration for this project/app.

The goal of `phpbu` for me was to configure the backup for each app, so the developer can influence the backup to his needs.

`phpbu` is not primarily designed for global backups. Maybe you can use it for something like that, but that's currently not the main goal of `phpbu`.
