### ISSUE TITLE
Excluding folders from TAR

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#99]
I am trying to setup the exclude option on the TAR but it does not seem to work. 

Do you have any examples?

Thanks!

**Comment by sebastianfeldmann** [comment]
I'll have a look when I get home, I'm currently on my way back to Munich ;)

**Comment by planetahuevo** [comment]
No problem. I will keep trying and paste here if I find a solution.
👍

**Comment by sebastianfeldmann** [comment]
Hi, here is a woking example.
```xml
<source type="tar">
  <option name="path" value="/some/crap"/>
  <option name="exclude" value="foo.*"/>
</source>
```
This excludes all files starting with `foo.` from the tar file.
Tested this with a directory containing `foo.txt` and `foo.php` and both where not packed in the tar file.

Maybe post your source config, so can try to reproduce something similar on my end.

**Comment by planetahuevo** [comment]
I was trying with this last night but I end too late to post it here. 
For folders I want to exclude on several subfolders I manage to do this (example for cache and tmp folders) which is useful for WordPress installation for example:
`<source type="tar">
  <option name="path" value="/some/crap"/>
  <option name="exclude" value="*/cache,*/cache/*,*/tmp/*,*/tmp"/>
</source>`

**Comment by sebastianfeldmann** [comment]
I opened an issue for the documentation repository.
Will close this here, thanks for the feedback ;)
